// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/RSODA/subscribe-manager/internal/repository.SubscriptionRepository -o subscription_repository_minimock.go -n SubscriptionRepositoryMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	"time"
	mm_time "time"

	"github.com/RSODA/subscribe-manager/internal/domain"
	"github.com/gojuno/minimock/v3"
)

// SubscriptionRepositoryMock implements mm_repository.SubscriptionRepository
type SubscriptionRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, sub *domain.Subscription) (sp1 *domain.Subscription, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, sub *domain.Subscription)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mSubscriptionRepositoryMockCreate

	funcDelete          func(ctx context.Context, id string) (err error)
	funcDeleteOrigin    string
	inspectFuncDelete   func(ctx context.Context, id string)
	afterDeleteCounter  uint64
	beforeDeleteCounter uint64
	DeleteMock          mSubscriptionRepositoryMockDelete

	funcGetAll          func(ctx context.Context) (spa1 []*domain.Subscription, err error)
	funcGetAllOrigin    string
	inspectFuncGetAll   func(ctx context.Context)
	afterGetAllCounter  uint64
	beforeGetAllCounter uint64
	GetAllMock          mSubscriptionRepositoryMockGetAll

	funcGetByID          func(ctx context.Context, id string) (sp1 *domain.Subscription, err error)
	funcGetByIDOrigin    string
	inspectFuncGetByID   func(ctx context.Context, id string)
	afterGetByIDCounter  uint64
	beforeGetByIDCounter uint64
	GetByIDMock          mSubscriptionRepositoryMockGetByID

	funcTotalCost          func(ctx context.Context, userID *string, serviceName *string, from *time.Time, to *time.Time) (i1 int, err error)
	funcTotalCostOrigin    string
	inspectFuncTotalCost   func(ctx context.Context, userID *string, serviceName *string, from *time.Time, to *time.Time)
	afterTotalCostCounter  uint64
	beforeTotalCostCounter uint64
	TotalCostMock          mSubscriptionRepositoryMockTotalCost

	funcUpdate          func(ctx context.Context, sub *domain.Subscription) (sp1 *domain.Subscription, err error)
	funcUpdateOrigin    string
	inspectFuncUpdate   func(ctx context.Context, sub *domain.Subscription)
	afterUpdateCounter  uint64
	beforeUpdateCounter uint64
	UpdateMock          mSubscriptionRepositoryMockUpdate
}

// NewSubscriptionRepositoryMock returns a mock for mm_repository.SubscriptionRepository
func NewSubscriptionRepositoryMock(t minimock.Tester) *SubscriptionRepositoryMock {
	m := &SubscriptionRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mSubscriptionRepositoryMockCreate{mock: m}
	m.CreateMock.callArgs = []*SubscriptionRepositoryMockCreateParams{}

	m.DeleteMock = mSubscriptionRepositoryMockDelete{mock: m}
	m.DeleteMock.callArgs = []*SubscriptionRepositoryMockDeleteParams{}

	m.GetAllMock = mSubscriptionRepositoryMockGetAll{mock: m}
	m.GetAllMock.callArgs = []*SubscriptionRepositoryMockGetAllParams{}

	m.GetByIDMock = mSubscriptionRepositoryMockGetByID{mock: m}
	m.GetByIDMock.callArgs = []*SubscriptionRepositoryMockGetByIDParams{}

	m.TotalCostMock = mSubscriptionRepositoryMockTotalCost{mock: m}
	m.TotalCostMock.callArgs = []*SubscriptionRepositoryMockTotalCostParams{}

	m.UpdateMock = mSubscriptionRepositoryMockUpdate{mock: m}
	m.UpdateMock.callArgs = []*SubscriptionRepositoryMockUpdateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mSubscriptionRepositoryMockCreate struct {
	optional           bool
	mock               *SubscriptionRepositoryMock
	defaultExpectation *SubscriptionRepositoryMockCreateExpectation
	expectations       []*SubscriptionRepositoryMockCreateExpectation

	callArgs []*SubscriptionRepositoryMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SubscriptionRepositoryMockCreateExpectation specifies expectation struct of the SubscriptionRepository.Create
type SubscriptionRepositoryMockCreateExpectation struct {
	mock               *SubscriptionRepositoryMock
	params             *SubscriptionRepositoryMockCreateParams
	paramPtrs          *SubscriptionRepositoryMockCreateParamPtrs
	expectationOrigins SubscriptionRepositoryMockCreateExpectationOrigins
	results            *SubscriptionRepositoryMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// SubscriptionRepositoryMockCreateParams contains parameters of the SubscriptionRepository.Create
type SubscriptionRepositoryMockCreateParams struct {
	ctx context.Context
	sub *domain.Subscription
}

// SubscriptionRepositoryMockCreateParamPtrs contains pointers to parameters of the SubscriptionRepository.Create
type SubscriptionRepositoryMockCreateParamPtrs struct {
	ctx *context.Context
	sub **domain.Subscription
}

// SubscriptionRepositoryMockCreateResults contains results of the SubscriptionRepository.Create
type SubscriptionRepositoryMockCreateResults struct {
	sp1 *domain.Subscription
	err error
}

// SubscriptionRepositoryMockCreateOrigins contains origins of expectations of the SubscriptionRepository.Create
type SubscriptionRepositoryMockCreateExpectationOrigins struct {
	origin    string
	originCtx string
	originSub string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mSubscriptionRepositoryMockCreate) Optional() *mSubscriptionRepositoryMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for SubscriptionRepository.Create
func (mmCreate *mSubscriptionRepositoryMockCreate) Expect(ctx context.Context, sub *domain.Subscription) *mSubscriptionRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("SubscriptionRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &SubscriptionRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("SubscriptionRepositoryMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &SubscriptionRepositoryMockCreateParams{ctx, sub}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for SubscriptionRepository.Create
func (mmCreate *mSubscriptionRepositoryMockCreate) ExpectCtxParam1(ctx context.Context) *mSubscriptionRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("SubscriptionRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &SubscriptionRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("SubscriptionRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &SubscriptionRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectSubParam2 sets up expected param sub for SubscriptionRepository.Create
func (mmCreate *mSubscriptionRepositoryMockCreate) ExpectSubParam2(sub *domain.Subscription) *mSubscriptionRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("SubscriptionRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &SubscriptionRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("SubscriptionRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &SubscriptionRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.sub = &sub
	mmCreate.defaultExpectation.expectationOrigins.originSub = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the SubscriptionRepository.Create
func (mmCreate *mSubscriptionRepositoryMockCreate) Inspect(f func(ctx context.Context, sub *domain.Subscription)) *mSubscriptionRepositoryMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for SubscriptionRepositoryMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by SubscriptionRepository.Create
func (mmCreate *mSubscriptionRepositoryMockCreate) Return(sp1 *domain.Subscription, err error) *SubscriptionRepositoryMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("SubscriptionRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &SubscriptionRepositoryMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &SubscriptionRepositoryMockCreateResults{sp1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the SubscriptionRepository.Create method
func (mmCreate *mSubscriptionRepositoryMockCreate) Set(f func(ctx context.Context, sub *domain.Subscription) (sp1 *domain.Subscription, err error)) *SubscriptionRepositoryMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the SubscriptionRepository.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the SubscriptionRepository.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the SubscriptionRepository.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mSubscriptionRepositoryMockCreate) When(ctx context.Context, sub *domain.Subscription) *SubscriptionRepositoryMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("SubscriptionRepositoryMock.Create mock is already set by Set")
	}

	expectation := &SubscriptionRepositoryMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &SubscriptionRepositoryMockCreateParams{ctx, sub},
		expectationOrigins: SubscriptionRepositoryMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up SubscriptionRepository.Create return parameters for the expectation previously defined by the When method
func (e *SubscriptionRepositoryMockCreateExpectation) Then(sp1 *domain.Subscription, err error) *SubscriptionRepositoryMock {
	e.results = &SubscriptionRepositoryMockCreateResults{sp1, err}
	return e.mock
}

// Times sets number of times SubscriptionRepository.Create should be invoked
func (mmCreate *mSubscriptionRepositoryMockCreate) Times(n uint64) *mSubscriptionRepositoryMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of SubscriptionRepositoryMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mSubscriptionRepositoryMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_repository.SubscriptionRepository
func (mmCreate *SubscriptionRepositoryMock) Create(ctx context.Context, sub *domain.Subscription) (sp1 *domain.Subscription, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, sub)
	}

	mm_params := SubscriptionRepositoryMockCreateParams{ctx, sub}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := SubscriptionRepositoryMockCreateParams{ctx, sub}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("SubscriptionRepositoryMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sub != nil && !minimock.Equal(*mm_want_ptrs.sub, mm_got.sub) {
				mmCreate.t.Errorf("SubscriptionRepositoryMock.Create got unexpected parameter sub, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originSub, *mm_want_ptrs.sub, mm_got.sub, minimock.Diff(*mm_want_ptrs.sub, mm_got.sub))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("SubscriptionRepositoryMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the SubscriptionRepositoryMock.Create")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, sub)
	}
	mmCreate.t.Fatalf("Unexpected call to SubscriptionRepositoryMock.Create. %v %v", ctx, sub)
	return
}

// CreateAfterCounter returns a count of finished SubscriptionRepositoryMock.Create invocations
func (mmCreate *SubscriptionRepositoryMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of SubscriptionRepositoryMock.Create invocations
func (mmCreate *SubscriptionRepositoryMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to SubscriptionRepositoryMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mSubscriptionRepositoryMockCreate) Calls() []*SubscriptionRepositoryMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*SubscriptionRepositoryMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *SubscriptionRepositoryMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *SubscriptionRepositoryMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to SubscriptionRepositoryMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to SubscriptionRepositoryMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mSubscriptionRepositoryMockDelete struct {
	optional           bool
	mock               *SubscriptionRepositoryMock
	defaultExpectation *SubscriptionRepositoryMockDeleteExpectation
	expectations       []*SubscriptionRepositoryMockDeleteExpectation

	callArgs []*SubscriptionRepositoryMockDeleteParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SubscriptionRepositoryMockDeleteExpectation specifies expectation struct of the SubscriptionRepository.Delete
type SubscriptionRepositoryMockDeleteExpectation struct {
	mock               *SubscriptionRepositoryMock
	params             *SubscriptionRepositoryMockDeleteParams
	paramPtrs          *SubscriptionRepositoryMockDeleteParamPtrs
	expectationOrigins SubscriptionRepositoryMockDeleteExpectationOrigins
	results            *SubscriptionRepositoryMockDeleteResults
	returnOrigin       string
	Counter            uint64
}

// SubscriptionRepositoryMockDeleteParams contains parameters of the SubscriptionRepository.Delete
type SubscriptionRepositoryMockDeleteParams struct {
	ctx context.Context
	id  string
}

// SubscriptionRepositoryMockDeleteParamPtrs contains pointers to parameters of the SubscriptionRepository.Delete
type SubscriptionRepositoryMockDeleteParamPtrs struct {
	ctx *context.Context
	id  *string
}

// SubscriptionRepositoryMockDeleteResults contains results of the SubscriptionRepository.Delete
type SubscriptionRepositoryMockDeleteResults struct {
	err error
}

// SubscriptionRepositoryMockDeleteOrigins contains origins of expectations of the SubscriptionRepository.Delete
type SubscriptionRepositoryMockDeleteExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDelete *mSubscriptionRepositoryMockDelete) Optional() *mSubscriptionRepositoryMockDelete {
	mmDelete.optional = true
	return mmDelete
}

// Expect sets up expected params for SubscriptionRepository.Delete
func (mmDelete *mSubscriptionRepositoryMockDelete) Expect(ctx context.Context, id string) *mSubscriptionRepositoryMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("SubscriptionRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &SubscriptionRepositoryMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.paramPtrs != nil {
		mmDelete.mock.t.Fatalf("SubscriptionRepositoryMock.Delete mock is already set by ExpectParams functions")
	}

	mmDelete.defaultExpectation.params = &SubscriptionRepositoryMockDeleteParams{ctx, id}
	mmDelete.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDelete.expectations {
		if minimock.Equal(e.params, mmDelete.defaultExpectation.params) {
			mmDelete.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDelete.defaultExpectation.params)
		}
	}

	return mmDelete
}

// ExpectCtxParam1 sets up expected param ctx for SubscriptionRepository.Delete
func (mmDelete *mSubscriptionRepositoryMockDelete) ExpectCtxParam1(ctx context.Context) *mSubscriptionRepositoryMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("SubscriptionRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &SubscriptionRepositoryMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("SubscriptionRepositoryMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &SubscriptionRepositoryMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.ctx = &ctx
	mmDelete.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectIdParam2 sets up expected param id for SubscriptionRepository.Delete
func (mmDelete *mSubscriptionRepositoryMockDelete) ExpectIdParam2(id string) *mSubscriptionRepositoryMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("SubscriptionRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &SubscriptionRepositoryMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("SubscriptionRepositoryMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &SubscriptionRepositoryMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.id = &id
	mmDelete.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmDelete
}

// Inspect accepts an inspector function that has same arguments as the SubscriptionRepository.Delete
func (mmDelete *mSubscriptionRepositoryMockDelete) Inspect(f func(ctx context.Context, id string)) *mSubscriptionRepositoryMockDelete {
	if mmDelete.mock.inspectFuncDelete != nil {
		mmDelete.mock.t.Fatalf("Inspect function is already set for SubscriptionRepositoryMock.Delete")
	}

	mmDelete.mock.inspectFuncDelete = f

	return mmDelete
}

// Return sets up results that will be returned by SubscriptionRepository.Delete
func (mmDelete *mSubscriptionRepositoryMockDelete) Return(err error) *SubscriptionRepositoryMock {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("SubscriptionRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &SubscriptionRepositoryMockDeleteExpectation{mock: mmDelete.mock}
	}
	mmDelete.defaultExpectation.results = &SubscriptionRepositoryMockDeleteResults{err}
	mmDelete.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// Set uses given function f to mock the SubscriptionRepository.Delete method
func (mmDelete *mSubscriptionRepositoryMockDelete) Set(f func(ctx context.Context, id string) (err error)) *SubscriptionRepositoryMock {
	if mmDelete.defaultExpectation != nil {
		mmDelete.mock.t.Fatalf("Default expectation is already set for the SubscriptionRepository.Delete method")
	}

	if len(mmDelete.expectations) > 0 {
		mmDelete.mock.t.Fatalf("Some expectations are already set for the SubscriptionRepository.Delete method")
	}

	mmDelete.mock.funcDelete = f
	mmDelete.mock.funcDeleteOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// When sets expectation for the SubscriptionRepository.Delete which will trigger the result defined by the following
// Then helper
func (mmDelete *mSubscriptionRepositoryMockDelete) When(ctx context.Context, id string) *SubscriptionRepositoryMockDeleteExpectation {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("SubscriptionRepositoryMock.Delete mock is already set by Set")
	}

	expectation := &SubscriptionRepositoryMockDeleteExpectation{
		mock:               mmDelete.mock,
		params:             &SubscriptionRepositoryMockDeleteParams{ctx, id},
		expectationOrigins: SubscriptionRepositoryMockDeleteExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDelete.expectations = append(mmDelete.expectations, expectation)
	return expectation
}

// Then sets up SubscriptionRepository.Delete return parameters for the expectation previously defined by the When method
func (e *SubscriptionRepositoryMockDeleteExpectation) Then(err error) *SubscriptionRepositoryMock {
	e.results = &SubscriptionRepositoryMockDeleteResults{err}
	return e.mock
}

// Times sets number of times SubscriptionRepository.Delete should be invoked
func (mmDelete *mSubscriptionRepositoryMockDelete) Times(n uint64) *mSubscriptionRepositoryMockDelete {
	if n == 0 {
		mmDelete.mock.t.Fatalf("Times of SubscriptionRepositoryMock.Delete mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDelete.expectedInvocations, n)
	mmDelete.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDelete
}

func (mmDelete *mSubscriptionRepositoryMockDelete) invocationsDone() bool {
	if len(mmDelete.expectations) == 0 && mmDelete.defaultExpectation == nil && mmDelete.mock.funcDelete == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDelete.mock.afterDeleteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDelete.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Delete implements mm_repository.SubscriptionRepository
func (mmDelete *SubscriptionRepositoryMock) Delete(ctx context.Context, id string) (err error) {
	mm_atomic.AddUint64(&mmDelete.beforeDeleteCounter, 1)
	defer mm_atomic.AddUint64(&mmDelete.afterDeleteCounter, 1)

	mmDelete.t.Helper()

	if mmDelete.inspectFuncDelete != nil {
		mmDelete.inspectFuncDelete(ctx, id)
	}

	mm_params := SubscriptionRepositoryMockDeleteParams{ctx, id}

	// Record call args
	mmDelete.DeleteMock.mutex.Lock()
	mmDelete.DeleteMock.callArgs = append(mmDelete.DeleteMock.callArgs, &mm_params)
	mmDelete.DeleteMock.mutex.Unlock()

	for _, e := range mmDelete.DeleteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDelete.DeleteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDelete.DeleteMock.defaultExpectation.Counter, 1)
		mm_want := mmDelete.DeleteMock.defaultExpectation.params
		mm_want_ptrs := mmDelete.DeleteMock.defaultExpectation.paramPtrs

		mm_got := SubscriptionRepositoryMockDeleteParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDelete.t.Errorf("SubscriptionRepositoryMock.Delete got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmDelete.t.Errorf("SubscriptionRepositoryMock.Delete got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDelete.t.Errorf("SubscriptionRepositoryMock.Delete got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDelete.DeleteMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDelete.DeleteMock.defaultExpectation.results
		if mm_results == nil {
			mmDelete.t.Fatal("No results are set for the SubscriptionRepositoryMock.Delete")
		}
		return (*mm_results).err
	}
	if mmDelete.funcDelete != nil {
		return mmDelete.funcDelete(ctx, id)
	}
	mmDelete.t.Fatalf("Unexpected call to SubscriptionRepositoryMock.Delete. %v %v", ctx, id)
	return
}

// DeleteAfterCounter returns a count of finished SubscriptionRepositoryMock.Delete invocations
func (mmDelete *SubscriptionRepositoryMock) DeleteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.afterDeleteCounter)
}

// DeleteBeforeCounter returns a count of SubscriptionRepositoryMock.Delete invocations
func (mmDelete *SubscriptionRepositoryMock) DeleteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.beforeDeleteCounter)
}

// Calls returns a list of arguments used in each call to SubscriptionRepositoryMock.Delete.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDelete *mSubscriptionRepositoryMockDelete) Calls() []*SubscriptionRepositoryMockDeleteParams {
	mmDelete.mutex.RLock()

	argCopy := make([]*SubscriptionRepositoryMockDeleteParams, len(mmDelete.callArgs))
	copy(argCopy, mmDelete.callArgs)

	mmDelete.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteDone returns true if the count of the Delete invocations corresponds
// the number of defined expectations
func (m *SubscriptionRepositoryMock) MinimockDeleteDone() bool {
	if m.DeleteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteMock.invocationsDone()
}

// MinimockDeleteInspect logs each unmet expectation
func (m *SubscriptionRepositoryMock) MinimockDeleteInspect() {
	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.Delete at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteCounter := mm_atomic.LoadUint64(&m.afterDeleteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteMock.defaultExpectation != nil && afterDeleteCounter < 1 {
		if m.DeleteMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.Delete at\n%s", m.DeleteMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.Delete at\n%s with params: %#v", m.DeleteMock.defaultExpectation.expectationOrigins.origin, *m.DeleteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDelete != nil && afterDeleteCounter < 1 {
		m.t.Errorf("Expected call to SubscriptionRepositoryMock.Delete at\n%s", m.funcDeleteOrigin)
	}

	if !m.DeleteMock.invocationsDone() && afterDeleteCounter > 0 {
		m.t.Errorf("Expected %d calls to SubscriptionRepositoryMock.Delete at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteMock.expectedInvocations), m.DeleteMock.expectedInvocationsOrigin, afterDeleteCounter)
	}
}

type mSubscriptionRepositoryMockGetAll struct {
	optional           bool
	mock               *SubscriptionRepositoryMock
	defaultExpectation *SubscriptionRepositoryMockGetAllExpectation
	expectations       []*SubscriptionRepositoryMockGetAllExpectation

	callArgs []*SubscriptionRepositoryMockGetAllParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SubscriptionRepositoryMockGetAllExpectation specifies expectation struct of the SubscriptionRepository.GetAll
type SubscriptionRepositoryMockGetAllExpectation struct {
	mock               *SubscriptionRepositoryMock
	params             *SubscriptionRepositoryMockGetAllParams
	paramPtrs          *SubscriptionRepositoryMockGetAllParamPtrs
	expectationOrigins SubscriptionRepositoryMockGetAllExpectationOrigins
	results            *SubscriptionRepositoryMockGetAllResults
	returnOrigin       string
	Counter            uint64
}

// SubscriptionRepositoryMockGetAllParams contains parameters of the SubscriptionRepository.GetAll
type SubscriptionRepositoryMockGetAllParams struct {
	ctx context.Context
}

// SubscriptionRepositoryMockGetAllParamPtrs contains pointers to parameters of the SubscriptionRepository.GetAll
type SubscriptionRepositoryMockGetAllParamPtrs struct {
	ctx *context.Context
}

// SubscriptionRepositoryMockGetAllResults contains results of the SubscriptionRepository.GetAll
type SubscriptionRepositoryMockGetAllResults struct {
	spa1 []*domain.Subscription
	err  error
}

// SubscriptionRepositoryMockGetAllOrigins contains origins of expectations of the SubscriptionRepository.GetAll
type SubscriptionRepositoryMockGetAllExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetAll *mSubscriptionRepositoryMockGetAll) Optional() *mSubscriptionRepositoryMockGetAll {
	mmGetAll.optional = true
	return mmGetAll
}

// Expect sets up expected params for SubscriptionRepository.GetAll
func (mmGetAll *mSubscriptionRepositoryMockGetAll) Expect(ctx context.Context) *mSubscriptionRepositoryMockGetAll {
	if mmGetAll.mock.funcGetAll != nil {
		mmGetAll.mock.t.Fatalf("SubscriptionRepositoryMock.GetAll mock is already set by Set")
	}

	if mmGetAll.defaultExpectation == nil {
		mmGetAll.defaultExpectation = &SubscriptionRepositoryMockGetAllExpectation{}
	}

	if mmGetAll.defaultExpectation.paramPtrs != nil {
		mmGetAll.mock.t.Fatalf("SubscriptionRepositoryMock.GetAll mock is already set by ExpectParams functions")
	}

	mmGetAll.defaultExpectation.params = &SubscriptionRepositoryMockGetAllParams{ctx}
	mmGetAll.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetAll.expectations {
		if minimock.Equal(e.params, mmGetAll.defaultExpectation.params) {
			mmGetAll.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetAll.defaultExpectation.params)
		}
	}

	return mmGetAll
}

// ExpectCtxParam1 sets up expected param ctx for SubscriptionRepository.GetAll
func (mmGetAll *mSubscriptionRepositoryMockGetAll) ExpectCtxParam1(ctx context.Context) *mSubscriptionRepositoryMockGetAll {
	if mmGetAll.mock.funcGetAll != nil {
		mmGetAll.mock.t.Fatalf("SubscriptionRepositoryMock.GetAll mock is already set by Set")
	}

	if mmGetAll.defaultExpectation == nil {
		mmGetAll.defaultExpectation = &SubscriptionRepositoryMockGetAllExpectation{}
	}

	if mmGetAll.defaultExpectation.params != nil {
		mmGetAll.mock.t.Fatalf("SubscriptionRepositoryMock.GetAll mock is already set by Expect")
	}

	if mmGetAll.defaultExpectation.paramPtrs == nil {
		mmGetAll.defaultExpectation.paramPtrs = &SubscriptionRepositoryMockGetAllParamPtrs{}
	}
	mmGetAll.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetAll.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetAll
}

// Inspect accepts an inspector function that has same arguments as the SubscriptionRepository.GetAll
func (mmGetAll *mSubscriptionRepositoryMockGetAll) Inspect(f func(ctx context.Context)) *mSubscriptionRepositoryMockGetAll {
	if mmGetAll.mock.inspectFuncGetAll != nil {
		mmGetAll.mock.t.Fatalf("Inspect function is already set for SubscriptionRepositoryMock.GetAll")
	}

	mmGetAll.mock.inspectFuncGetAll = f

	return mmGetAll
}

// Return sets up results that will be returned by SubscriptionRepository.GetAll
func (mmGetAll *mSubscriptionRepositoryMockGetAll) Return(spa1 []*domain.Subscription, err error) *SubscriptionRepositoryMock {
	if mmGetAll.mock.funcGetAll != nil {
		mmGetAll.mock.t.Fatalf("SubscriptionRepositoryMock.GetAll mock is already set by Set")
	}

	if mmGetAll.defaultExpectation == nil {
		mmGetAll.defaultExpectation = &SubscriptionRepositoryMockGetAllExpectation{mock: mmGetAll.mock}
	}
	mmGetAll.defaultExpectation.results = &SubscriptionRepositoryMockGetAllResults{spa1, err}
	mmGetAll.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetAll.mock
}

// Set uses given function f to mock the SubscriptionRepository.GetAll method
func (mmGetAll *mSubscriptionRepositoryMockGetAll) Set(f func(ctx context.Context) (spa1 []*domain.Subscription, err error)) *SubscriptionRepositoryMock {
	if mmGetAll.defaultExpectation != nil {
		mmGetAll.mock.t.Fatalf("Default expectation is already set for the SubscriptionRepository.GetAll method")
	}

	if len(mmGetAll.expectations) > 0 {
		mmGetAll.mock.t.Fatalf("Some expectations are already set for the SubscriptionRepository.GetAll method")
	}

	mmGetAll.mock.funcGetAll = f
	mmGetAll.mock.funcGetAllOrigin = minimock.CallerInfo(1)
	return mmGetAll.mock
}

// When sets expectation for the SubscriptionRepository.GetAll which will trigger the result defined by the following
// Then helper
func (mmGetAll *mSubscriptionRepositoryMockGetAll) When(ctx context.Context) *SubscriptionRepositoryMockGetAllExpectation {
	if mmGetAll.mock.funcGetAll != nil {
		mmGetAll.mock.t.Fatalf("SubscriptionRepositoryMock.GetAll mock is already set by Set")
	}

	expectation := &SubscriptionRepositoryMockGetAllExpectation{
		mock:               mmGetAll.mock,
		params:             &SubscriptionRepositoryMockGetAllParams{ctx},
		expectationOrigins: SubscriptionRepositoryMockGetAllExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetAll.expectations = append(mmGetAll.expectations, expectation)
	return expectation
}

// Then sets up SubscriptionRepository.GetAll return parameters for the expectation previously defined by the When method
func (e *SubscriptionRepositoryMockGetAllExpectation) Then(spa1 []*domain.Subscription, err error) *SubscriptionRepositoryMock {
	e.results = &SubscriptionRepositoryMockGetAllResults{spa1, err}
	return e.mock
}

// Times sets number of times SubscriptionRepository.GetAll should be invoked
func (mmGetAll *mSubscriptionRepositoryMockGetAll) Times(n uint64) *mSubscriptionRepositoryMockGetAll {
	if n == 0 {
		mmGetAll.mock.t.Fatalf("Times of SubscriptionRepositoryMock.GetAll mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetAll.expectedInvocations, n)
	mmGetAll.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetAll
}

func (mmGetAll *mSubscriptionRepositoryMockGetAll) invocationsDone() bool {
	if len(mmGetAll.expectations) == 0 && mmGetAll.defaultExpectation == nil && mmGetAll.mock.funcGetAll == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetAll.mock.afterGetAllCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetAll.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetAll implements mm_repository.SubscriptionRepository
func (mmGetAll *SubscriptionRepositoryMock) GetAll(ctx context.Context) (spa1 []*domain.Subscription, err error) {
	mm_atomic.AddUint64(&mmGetAll.beforeGetAllCounter, 1)
	defer mm_atomic.AddUint64(&mmGetAll.afterGetAllCounter, 1)

	mmGetAll.t.Helper()

	if mmGetAll.inspectFuncGetAll != nil {
		mmGetAll.inspectFuncGetAll(ctx)
	}

	mm_params := SubscriptionRepositoryMockGetAllParams{ctx}

	// Record call args
	mmGetAll.GetAllMock.mutex.Lock()
	mmGetAll.GetAllMock.callArgs = append(mmGetAll.GetAllMock.callArgs, &mm_params)
	mmGetAll.GetAllMock.mutex.Unlock()

	for _, e := range mmGetAll.GetAllMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.spa1, e.results.err
		}
	}

	if mmGetAll.GetAllMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetAll.GetAllMock.defaultExpectation.Counter, 1)
		mm_want := mmGetAll.GetAllMock.defaultExpectation.params
		mm_want_ptrs := mmGetAll.GetAllMock.defaultExpectation.paramPtrs

		mm_got := SubscriptionRepositoryMockGetAllParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetAll.t.Errorf("SubscriptionRepositoryMock.GetAll got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetAll.GetAllMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetAll.t.Errorf("SubscriptionRepositoryMock.GetAll got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetAll.GetAllMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetAll.GetAllMock.defaultExpectation.results
		if mm_results == nil {
			mmGetAll.t.Fatal("No results are set for the SubscriptionRepositoryMock.GetAll")
		}
		return (*mm_results).spa1, (*mm_results).err
	}
	if mmGetAll.funcGetAll != nil {
		return mmGetAll.funcGetAll(ctx)
	}
	mmGetAll.t.Fatalf("Unexpected call to SubscriptionRepositoryMock.GetAll. %v", ctx)
	return
}

// GetAllAfterCounter returns a count of finished SubscriptionRepositoryMock.GetAll invocations
func (mmGetAll *SubscriptionRepositoryMock) GetAllAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAll.afterGetAllCounter)
}

// GetAllBeforeCounter returns a count of SubscriptionRepositoryMock.GetAll invocations
func (mmGetAll *SubscriptionRepositoryMock) GetAllBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAll.beforeGetAllCounter)
}

// Calls returns a list of arguments used in each call to SubscriptionRepositoryMock.GetAll.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetAll *mSubscriptionRepositoryMockGetAll) Calls() []*SubscriptionRepositoryMockGetAllParams {
	mmGetAll.mutex.RLock()

	argCopy := make([]*SubscriptionRepositoryMockGetAllParams, len(mmGetAll.callArgs))
	copy(argCopy, mmGetAll.callArgs)

	mmGetAll.mutex.RUnlock()

	return argCopy
}

// MinimockGetAllDone returns true if the count of the GetAll invocations corresponds
// the number of defined expectations
func (m *SubscriptionRepositoryMock) MinimockGetAllDone() bool {
	if m.GetAllMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetAllMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetAllMock.invocationsDone()
}

// MinimockGetAllInspect logs each unmet expectation
func (m *SubscriptionRepositoryMock) MinimockGetAllInspect() {
	for _, e := range m.GetAllMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.GetAll at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetAllCounter := mm_atomic.LoadUint64(&m.afterGetAllCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetAllMock.defaultExpectation != nil && afterGetAllCounter < 1 {
		if m.GetAllMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.GetAll at\n%s", m.GetAllMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.GetAll at\n%s with params: %#v", m.GetAllMock.defaultExpectation.expectationOrigins.origin, *m.GetAllMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAll != nil && afterGetAllCounter < 1 {
		m.t.Errorf("Expected call to SubscriptionRepositoryMock.GetAll at\n%s", m.funcGetAllOrigin)
	}

	if !m.GetAllMock.invocationsDone() && afterGetAllCounter > 0 {
		m.t.Errorf("Expected %d calls to SubscriptionRepositoryMock.GetAll at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetAllMock.expectedInvocations), m.GetAllMock.expectedInvocationsOrigin, afterGetAllCounter)
	}
}

type mSubscriptionRepositoryMockGetByID struct {
	optional           bool
	mock               *SubscriptionRepositoryMock
	defaultExpectation *SubscriptionRepositoryMockGetByIDExpectation
	expectations       []*SubscriptionRepositoryMockGetByIDExpectation

	callArgs []*SubscriptionRepositoryMockGetByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SubscriptionRepositoryMockGetByIDExpectation specifies expectation struct of the SubscriptionRepository.GetByID
type SubscriptionRepositoryMockGetByIDExpectation struct {
	mock               *SubscriptionRepositoryMock
	params             *SubscriptionRepositoryMockGetByIDParams
	paramPtrs          *SubscriptionRepositoryMockGetByIDParamPtrs
	expectationOrigins SubscriptionRepositoryMockGetByIDExpectationOrigins
	results            *SubscriptionRepositoryMockGetByIDResults
	returnOrigin       string
	Counter            uint64
}

// SubscriptionRepositoryMockGetByIDParams contains parameters of the SubscriptionRepository.GetByID
type SubscriptionRepositoryMockGetByIDParams struct {
	ctx context.Context
	id  string
}

// SubscriptionRepositoryMockGetByIDParamPtrs contains pointers to parameters of the SubscriptionRepository.GetByID
type SubscriptionRepositoryMockGetByIDParamPtrs struct {
	ctx *context.Context
	id  *string
}

// SubscriptionRepositoryMockGetByIDResults contains results of the SubscriptionRepository.GetByID
type SubscriptionRepositoryMockGetByIDResults struct {
	sp1 *domain.Subscription
	err error
}

// SubscriptionRepositoryMockGetByIDOrigins contains origins of expectations of the SubscriptionRepository.GetByID
type SubscriptionRepositoryMockGetByIDExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByID *mSubscriptionRepositoryMockGetByID) Optional() *mSubscriptionRepositoryMockGetByID {
	mmGetByID.optional = true
	return mmGetByID
}

// Expect sets up expected params for SubscriptionRepository.GetByID
func (mmGetByID *mSubscriptionRepositoryMockGetByID) Expect(ctx context.Context, id string) *mSubscriptionRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &SubscriptionRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.paramPtrs != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionRepositoryMock.GetByID mock is already set by ExpectParams functions")
	}

	mmGetByID.defaultExpectation.params = &SubscriptionRepositoryMockGetByIDParams{ctx, id}
	mmGetByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByID.expectations {
		if minimock.Equal(e.params, mmGetByID.defaultExpectation.params) {
			mmGetByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByID.defaultExpectation.params)
		}
	}

	return mmGetByID
}

// ExpectCtxParam1 sets up expected param ctx for SubscriptionRepository.GetByID
func (mmGetByID *mSubscriptionRepositoryMockGetByID) ExpectCtxParam1(ctx context.Context) *mSubscriptionRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &SubscriptionRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &SubscriptionRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByID
}

// ExpectIdParam2 sets up expected param id for SubscriptionRepository.GetByID
func (mmGetByID *mSubscriptionRepositoryMockGetByID) ExpectIdParam2(id string) *mSubscriptionRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &SubscriptionRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &SubscriptionRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.id = &id
	mmGetByID.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetByID
}

// Inspect accepts an inspector function that has same arguments as the SubscriptionRepository.GetByID
func (mmGetByID *mSubscriptionRepositoryMockGetByID) Inspect(f func(ctx context.Context, id string)) *mSubscriptionRepositoryMockGetByID {
	if mmGetByID.mock.inspectFuncGetByID != nil {
		mmGetByID.mock.t.Fatalf("Inspect function is already set for SubscriptionRepositoryMock.GetByID")
	}

	mmGetByID.mock.inspectFuncGetByID = f

	return mmGetByID
}

// Return sets up results that will be returned by SubscriptionRepository.GetByID
func (mmGetByID *mSubscriptionRepositoryMockGetByID) Return(sp1 *domain.Subscription, err error) *SubscriptionRepositoryMock {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &SubscriptionRepositoryMockGetByIDExpectation{mock: mmGetByID.mock}
	}
	mmGetByID.defaultExpectation.results = &SubscriptionRepositoryMockGetByIDResults{sp1, err}
	mmGetByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// Set uses given function f to mock the SubscriptionRepository.GetByID method
func (mmGetByID *mSubscriptionRepositoryMockGetByID) Set(f func(ctx context.Context, id string) (sp1 *domain.Subscription, err error)) *SubscriptionRepositoryMock {
	if mmGetByID.defaultExpectation != nil {
		mmGetByID.mock.t.Fatalf("Default expectation is already set for the SubscriptionRepository.GetByID method")
	}

	if len(mmGetByID.expectations) > 0 {
		mmGetByID.mock.t.Fatalf("Some expectations are already set for the SubscriptionRepository.GetByID method")
	}

	mmGetByID.mock.funcGetByID = f
	mmGetByID.mock.funcGetByIDOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// When sets expectation for the SubscriptionRepository.GetByID which will trigger the result defined by the following
// Then helper
func (mmGetByID *mSubscriptionRepositoryMockGetByID) When(ctx context.Context, id string) *SubscriptionRepositoryMockGetByIDExpectation {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionRepositoryMock.GetByID mock is already set by Set")
	}

	expectation := &SubscriptionRepositoryMockGetByIDExpectation{
		mock:               mmGetByID.mock,
		params:             &SubscriptionRepositoryMockGetByIDParams{ctx, id},
		expectationOrigins: SubscriptionRepositoryMockGetByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByID.expectations = append(mmGetByID.expectations, expectation)
	return expectation
}

// Then sets up SubscriptionRepository.GetByID return parameters for the expectation previously defined by the When method
func (e *SubscriptionRepositoryMockGetByIDExpectation) Then(sp1 *domain.Subscription, err error) *SubscriptionRepositoryMock {
	e.results = &SubscriptionRepositoryMockGetByIDResults{sp1, err}
	return e.mock
}

// Times sets number of times SubscriptionRepository.GetByID should be invoked
func (mmGetByID *mSubscriptionRepositoryMockGetByID) Times(n uint64) *mSubscriptionRepositoryMockGetByID {
	if n == 0 {
		mmGetByID.mock.t.Fatalf("Times of SubscriptionRepositoryMock.GetByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByID.expectedInvocations, n)
	mmGetByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByID
}

func (mmGetByID *mSubscriptionRepositoryMockGetByID) invocationsDone() bool {
	if len(mmGetByID.expectations) == 0 && mmGetByID.defaultExpectation == nil && mmGetByID.mock.funcGetByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByID.mock.afterGetByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByID implements mm_repository.SubscriptionRepository
func (mmGetByID *SubscriptionRepositoryMock) GetByID(ctx context.Context, id string) (sp1 *domain.Subscription, err error) {
	mm_atomic.AddUint64(&mmGetByID.beforeGetByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByID.afterGetByIDCounter, 1)

	mmGetByID.t.Helper()

	if mmGetByID.inspectFuncGetByID != nil {
		mmGetByID.inspectFuncGetByID(ctx, id)
	}

	mm_params := SubscriptionRepositoryMockGetByIDParams{ctx, id}

	// Record call args
	mmGetByID.GetByIDMock.mutex.Lock()
	mmGetByID.GetByIDMock.callArgs = append(mmGetByID.GetByIDMock.callArgs, &mm_params)
	mmGetByID.GetByIDMock.mutex.Unlock()

	for _, e := range mmGetByID.GetByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmGetByID.GetByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByID.GetByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByID.GetByIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByID.GetByIDMock.defaultExpectation.paramPtrs

		mm_got := SubscriptionRepositoryMockGetByIDParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByID.t.Errorf("SubscriptionRepositoryMock.GetByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetByID.t.Errorf("SubscriptionRepositoryMock.GetByID got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByID.t.Errorf("SubscriptionRepositoryMock.GetByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByID.GetByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByID.t.Fatal("No results are set for the SubscriptionRepositoryMock.GetByID")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmGetByID.funcGetByID != nil {
		return mmGetByID.funcGetByID(ctx, id)
	}
	mmGetByID.t.Fatalf("Unexpected call to SubscriptionRepositoryMock.GetByID. %v %v", ctx, id)
	return
}

// GetByIDAfterCounter returns a count of finished SubscriptionRepositoryMock.GetByID invocations
func (mmGetByID *SubscriptionRepositoryMock) GetByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.afterGetByIDCounter)
}

// GetByIDBeforeCounter returns a count of SubscriptionRepositoryMock.GetByID invocations
func (mmGetByID *SubscriptionRepositoryMock) GetByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.beforeGetByIDCounter)
}

// Calls returns a list of arguments used in each call to SubscriptionRepositoryMock.GetByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByID *mSubscriptionRepositoryMockGetByID) Calls() []*SubscriptionRepositoryMockGetByIDParams {
	mmGetByID.mutex.RLock()

	argCopy := make([]*SubscriptionRepositoryMockGetByIDParams, len(mmGetByID.callArgs))
	copy(argCopy, mmGetByID.callArgs)

	mmGetByID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByIDDone returns true if the count of the GetByID invocations corresponds
// the number of defined expectations
func (m *SubscriptionRepositoryMock) MinimockGetByIDDone() bool {
	if m.GetByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByIDMock.invocationsDone()
}

// MinimockGetByIDInspect logs each unmet expectation
func (m *SubscriptionRepositoryMock) MinimockGetByIDInspect() {
	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.GetByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByIDCounter := mm_atomic.LoadUint64(&m.afterGetByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByIDMock.defaultExpectation != nil && afterGetByIDCounter < 1 {
		if m.GetByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.GetByID at\n%s", m.GetByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.GetByID at\n%s with params: %#v", m.GetByIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByID != nil && afterGetByIDCounter < 1 {
		m.t.Errorf("Expected call to SubscriptionRepositoryMock.GetByID at\n%s", m.funcGetByIDOrigin)
	}

	if !m.GetByIDMock.invocationsDone() && afterGetByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to SubscriptionRepositoryMock.GetByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByIDMock.expectedInvocations), m.GetByIDMock.expectedInvocationsOrigin, afterGetByIDCounter)
	}
}

type mSubscriptionRepositoryMockTotalCost struct {
	optional           bool
	mock               *SubscriptionRepositoryMock
	defaultExpectation *SubscriptionRepositoryMockTotalCostExpectation
	expectations       []*SubscriptionRepositoryMockTotalCostExpectation

	callArgs []*SubscriptionRepositoryMockTotalCostParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SubscriptionRepositoryMockTotalCostExpectation specifies expectation struct of the SubscriptionRepository.TotalCost
type SubscriptionRepositoryMockTotalCostExpectation struct {
	mock               *SubscriptionRepositoryMock
	params             *SubscriptionRepositoryMockTotalCostParams
	paramPtrs          *SubscriptionRepositoryMockTotalCostParamPtrs
	expectationOrigins SubscriptionRepositoryMockTotalCostExpectationOrigins
	results            *SubscriptionRepositoryMockTotalCostResults
	returnOrigin       string
	Counter            uint64
}

// SubscriptionRepositoryMockTotalCostParams contains parameters of the SubscriptionRepository.TotalCost
type SubscriptionRepositoryMockTotalCostParams struct {
	ctx         context.Context
	userID      *string
	serviceName *string
	from        *time.Time
	to          *time.Time
}

// SubscriptionRepositoryMockTotalCostParamPtrs contains pointers to parameters of the SubscriptionRepository.TotalCost
type SubscriptionRepositoryMockTotalCostParamPtrs struct {
	ctx         *context.Context
	userID      **string
	serviceName **string
	from        **time.Time
	to          **time.Time
}

// SubscriptionRepositoryMockTotalCostResults contains results of the SubscriptionRepository.TotalCost
type SubscriptionRepositoryMockTotalCostResults struct {
	i1  int
	err error
}

// SubscriptionRepositoryMockTotalCostOrigins contains origins of expectations of the SubscriptionRepository.TotalCost
type SubscriptionRepositoryMockTotalCostExpectationOrigins struct {
	origin            string
	originCtx         string
	originUserID      string
	originServiceName string
	originFrom        string
	originTo          string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmTotalCost *mSubscriptionRepositoryMockTotalCost) Optional() *mSubscriptionRepositoryMockTotalCost {
	mmTotalCost.optional = true
	return mmTotalCost
}

// Expect sets up expected params for SubscriptionRepository.TotalCost
func (mmTotalCost *mSubscriptionRepositoryMockTotalCost) Expect(ctx context.Context, userID *string, serviceName *string, from *time.Time, to *time.Time) *mSubscriptionRepositoryMockTotalCost {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionRepositoryMock.TotalCost mock is already set by Set")
	}

	if mmTotalCost.defaultExpectation == nil {
		mmTotalCost.defaultExpectation = &SubscriptionRepositoryMockTotalCostExpectation{}
	}

	if mmTotalCost.defaultExpectation.paramPtrs != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionRepositoryMock.TotalCost mock is already set by ExpectParams functions")
	}

	mmTotalCost.defaultExpectation.params = &SubscriptionRepositoryMockTotalCostParams{ctx, userID, serviceName, from, to}
	mmTotalCost.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmTotalCost.expectations {
		if minimock.Equal(e.params, mmTotalCost.defaultExpectation.params) {
			mmTotalCost.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmTotalCost.defaultExpectation.params)
		}
	}

	return mmTotalCost
}

// ExpectCtxParam1 sets up expected param ctx for SubscriptionRepository.TotalCost
func (mmTotalCost *mSubscriptionRepositoryMockTotalCost) ExpectCtxParam1(ctx context.Context) *mSubscriptionRepositoryMockTotalCost {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionRepositoryMock.TotalCost mock is already set by Set")
	}

	if mmTotalCost.defaultExpectation == nil {
		mmTotalCost.defaultExpectation = &SubscriptionRepositoryMockTotalCostExpectation{}
	}

	if mmTotalCost.defaultExpectation.params != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionRepositoryMock.TotalCost mock is already set by Expect")
	}

	if mmTotalCost.defaultExpectation.paramPtrs == nil {
		mmTotalCost.defaultExpectation.paramPtrs = &SubscriptionRepositoryMockTotalCostParamPtrs{}
	}
	mmTotalCost.defaultExpectation.paramPtrs.ctx = &ctx
	mmTotalCost.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmTotalCost
}

// ExpectUserIDParam2 sets up expected param userID for SubscriptionRepository.TotalCost
func (mmTotalCost *mSubscriptionRepositoryMockTotalCost) ExpectUserIDParam2(userID *string) *mSubscriptionRepositoryMockTotalCost {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionRepositoryMock.TotalCost mock is already set by Set")
	}

	if mmTotalCost.defaultExpectation == nil {
		mmTotalCost.defaultExpectation = &SubscriptionRepositoryMockTotalCostExpectation{}
	}

	if mmTotalCost.defaultExpectation.params != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionRepositoryMock.TotalCost mock is already set by Expect")
	}

	if mmTotalCost.defaultExpectation.paramPtrs == nil {
		mmTotalCost.defaultExpectation.paramPtrs = &SubscriptionRepositoryMockTotalCostParamPtrs{}
	}
	mmTotalCost.defaultExpectation.paramPtrs.userID = &userID
	mmTotalCost.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmTotalCost
}

// ExpectServiceNameParam3 sets up expected param serviceName for SubscriptionRepository.TotalCost
func (mmTotalCost *mSubscriptionRepositoryMockTotalCost) ExpectServiceNameParam3(serviceName *string) *mSubscriptionRepositoryMockTotalCost {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionRepositoryMock.TotalCost mock is already set by Set")
	}

	if mmTotalCost.defaultExpectation == nil {
		mmTotalCost.defaultExpectation = &SubscriptionRepositoryMockTotalCostExpectation{}
	}

	if mmTotalCost.defaultExpectation.params != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionRepositoryMock.TotalCost mock is already set by Expect")
	}

	if mmTotalCost.defaultExpectation.paramPtrs == nil {
		mmTotalCost.defaultExpectation.paramPtrs = &SubscriptionRepositoryMockTotalCostParamPtrs{}
	}
	mmTotalCost.defaultExpectation.paramPtrs.serviceName = &serviceName
	mmTotalCost.defaultExpectation.expectationOrigins.originServiceName = minimock.CallerInfo(1)

	return mmTotalCost
}

// ExpectFromParam4 sets up expected param from for SubscriptionRepository.TotalCost
func (mmTotalCost *mSubscriptionRepositoryMockTotalCost) ExpectFromParam4(from *time.Time) *mSubscriptionRepositoryMockTotalCost {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionRepositoryMock.TotalCost mock is already set by Set")
	}

	if mmTotalCost.defaultExpectation == nil {
		mmTotalCost.defaultExpectation = &SubscriptionRepositoryMockTotalCostExpectation{}
	}

	if mmTotalCost.defaultExpectation.params != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionRepositoryMock.TotalCost mock is already set by Expect")
	}

	if mmTotalCost.defaultExpectation.paramPtrs == nil {
		mmTotalCost.defaultExpectation.paramPtrs = &SubscriptionRepositoryMockTotalCostParamPtrs{}
	}
	mmTotalCost.defaultExpectation.paramPtrs.from = &from
	mmTotalCost.defaultExpectation.expectationOrigins.originFrom = minimock.CallerInfo(1)

	return mmTotalCost
}

// ExpectToParam5 sets up expected param to for SubscriptionRepository.TotalCost
func (mmTotalCost *mSubscriptionRepositoryMockTotalCost) ExpectToParam5(to *time.Time) *mSubscriptionRepositoryMockTotalCost {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionRepositoryMock.TotalCost mock is already set by Set")
	}

	if mmTotalCost.defaultExpectation == nil {
		mmTotalCost.defaultExpectation = &SubscriptionRepositoryMockTotalCostExpectation{}
	}

	if mmTotalCost.defaultExpectation.params != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionRepositoryMock.TotalCost mock is already set by Expect")
	}

	if mmTotalCost.defaultExpectation.paramPtrs == nil {
		mmTotalCost.defaultExpectation.paramPtrs = &SubscriptionRepositoryMockTotalCostParamPtrs{}
	}
	mmTotalCost.defaultExpectation.paramPtrs.to = &to
	mmTotalCost.defaultExpectation.expectationOrigins.originTo = minimock.CallerInfo(1)

	return mmTotalCost
}

// Inspect accepts an inspector function that has same arguments as the SubscriptionRepository.TotalCost
func (mmTotalCost *mSubscriptionRepositoryMockTotalCost) Inspect(f func(ctx context.Context, userID *string, serviceName *string, from *time.Time, to *time.Time)) *mSubscriptionRepositoryMockTotalCost {
	if mmTotalCost.mock.inspectFuncTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("Inspect function is already set for SubscriptionRepositoryMock.TotalCost")
	}

	mmTotalCost.mock.inspectFuncTotalCost = f

	return mmTotalCost
}

// Return sets up results that will be returned by SubscriptionRepository.TotalCost
func (mmTotalCost *mSubscriptionRepositoryMockTotalCost) Return(i1 int, err error) *SubscriptionRepositoryMock {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionRepositoryMock.TotalCost mock is already set by Set")
	}

	if mmTotalCost.defaultExpectation == nil {
		mmTotalCost.defaultExpectation = &SubscriptionRepositoryMockTotalCostExpectation{mock: mmTotalCost.mock}
	}
	mmTotalCost.defaultExpectation.results = &SubscriptionRepositoryMockTotalCostResults{i1, err}
	mmTotalCost.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmTotalCost.mock
}

// Set uses given function f to mock the SubscriptionRepository.TotalCost method
func (mmTotalCost *mSubscriptionRepositoryMockTotalCost) Set(f func(ctx context.Context, userID *string, serviceName *string, from *time.Time, to *time.Time) (i1 int, err error)) *SubscriptionRepositoryMock {
	if mmTotalCost.defaultExpectation != nil {
		mmTotalCost.mock.t.Fatalf("Default expectation is already set for the SubscriptionRepository.TotalCost method")
	}

	if len(mmTotalCost.expectations) > 0 {
		mmTotalCost.mock.t.Fatalf("Some expectations are already set for the SubscriptionRepository.TotalCost method")
	}

	mmTotalCost.mock.funcTotalCost = f
	mmTotalCost.mock.funcTotalCostOrigin = minimock.CallerInfo(1)
	return mmTotalCost.mock
}

// When sets expectation for the SubscriptionRepository.TotalCost which will trigger the result defined by the following
// Then helper
func (mmTotalCost *mSubscriptionRepositoryMockTotalCost) When(ctx context.Context, userID *string, serviceName *string, from *time.Time, to *time.Time) *SubscriptionRepositoryMockTotalCostExpectation {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionRepositoryMock.TotalCost mock is already set by Set")
	}

	expectation := &SubscriptionRepositoryMockTotalCostExpectation{
		mock:               mmTotalCost.mock,
		params:             &SubscriptionRepositoryMockTotalCostParams{ctx, userID, serviceName, from, to},
		expectationOrigins: SubscriptionRepositoryMockTotalCostExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmTotalCost.expectations = append(mmTotalCost.expectations, expectation)
	return expectation
}

// Then sets up SubscriptionRepository.TotalCost return parameters for the expectation previously defined by the When method
func (e *SubscriptionRepositoryMockTotalCostExpectation) Then(i1 int, err error) *SubscriptionRepositoryMock {
	e.results = &SubscriptionRepositoryMockTotalCostResults{i1, err}
	return e.mock
}

// Times sets number of times SubscriptionRepository.TotalCost should be invoked
func (mmTotalCost *mSubscriptionRepositoryMockTotalCost) Times(n uint64) *mSubscriptionRepositoryMockTotalCost {
	if n == 0 {
		mmTotalCost.mock.t.Fatalf("Times of SubscriptionRepositoryMock.TotalCost mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmTotalCost.expectedInvocations, n)
	mmTotalCost.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmTotalCost
}

func (mmTotalCost *mSubscriptionRepositoryMockTotalCost) invocationsDone() bool {
	if len(mmTotalCost.expectations) == 0 && mmTotalCost.defaultExpectation == nil && mmTotalCost.mock.funcTotalCost == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmTotalCost.mock.afterTotalCostCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmTotalCost.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// TotalCost implements mm_repository.SubscriptionRepository
func (mmTotalCost *SubscriptionRepositoryMock) TotalCost(ctx context.Context, userID *string, serviceName *string, from *time.Time, to *time.Time) (i1 int, err error) {
	mm_atomic.AddUint64(&mmTotalCost.beforeTotalCostCounter, 1)
	defer mm_atomic.AddUint64(&mmTotalCost.afterTotalCostCounter, 1)

	mmTotalCost.t.Helper()

	if mmTotalCost.inspectFuncTotalCost != nil {
		mmTotalCost.inspectFuncTotalCost(ctx, userID, serviceName, from, to)
	}

	mm_params := SubscriptionRepositoryMockTotalCostParams{ctx, userID, serviceName, from, to}

	// Record call args
	mmTotalCost.TotalCostMock.mutex.Lock()
	mmTotalCost.TotalCostMock.callArgs = append(mmTotalCost.TotalCostMock.callArgs, &mm_params)
	mmTotalCost.TotalCostMock.mutex.Unlock()

	for _, e := range mmTotalCost.TotalCostMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmTotalCost.TotalCostMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmTotalCost.TotalCostMock.defaultExpectation.Counter, 1)
		mm_want := mmTotalCost.TotalCostMock.defaultExpectation.params
		mm_want_ptrs := mmTotalCost.TotalCostMock.defaultExpectation.paramPtrs

		mm_got := SubscriptionRepositoryMockTotalCostParams{ctx, userID, serviceName, from, to}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmTotalCost.t.Errorf("SubscriptionRepositoryMock.TotalCost got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmTotalCost.TotalCostMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmTotalCost.t.Errorf("SubscriptionRepositoryMock.TotalCost got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmTotalCost.TotalCostMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.serviceName != nil && !minimock.Equal(*mm_want_ptrs.serviceName, mm_got.serviceName) {
				mmTotalCost.t.Errorf("SubscriptionRepositoryMock.TotalCost got unexpected parameter serviceName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmTotalCost.TotalCostMock.defaultExpectation.expectationOrigins.originServiceName, *mm_want_ptrs.serviceName, mm_got.serviceName, minimock.Diff(*mm_want_ptrs.serviceName, mm_got.serviceName))
			}

			if mm_want_ptrs.from != nil && !minimock.Equal(*mm_want_ptrs.from, mm_got.from) {
				mmTotalCost.t.Errorf("SubscriptionRepositoryMock.TotalCost got unexpected parameter from, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmTotalCost.TotalCostMock.defaultExpectation.expectationOrigins.originFrom, *mm_want_ptrs.from, mm_got.from, minimock.Diff(*mm_want_ptrs.from, mm_got.from))
			}

			if mm_want_ptrs.to != nil && !minimock.Equal(*mm_want_ptrs.to, mm_got.to) {
				mmTotalCost.t.Errorf("SubscriptionRepositoryMock.TotalCost got unexpected parameter to, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmTotalCost.TotalCostMock.defaultExpectation.expectationOrigins.originTo, *mm_want_ptrs.to, mm_got.to, minimock.Diff(*mm_want_ptrs.to, mm_got.to))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmTotalCost.t.Errorf("SubscriptionRepositoryMock.TotalCost got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmTotalCost.TotalCostMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmTotalCost.TotalCostMock.defaultExpectation.results
		if mm_results == nil {
			mmTotalCost.t.Fatal("No results are set for the SubscriptionRepositoryMock.TotalCost")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmTotalCost.funcTotalCost != nil {
		return mmTotalCost.funcTotalCost(ctx, userID, serviceName, from, to)
	}
	mmTotalCost.t.Fatalf("Unexpected call to SubscriptionRepositoryMock.TotalCost. %v %v %v %v %v", ctx, userID, serviceName, from, to)
	return
}

// TotalCostAfterCounter returns a count of finished SubscriptionRepositoryMock.TotalCost invocations
func (mmTotalCost *SubscriptionRepositoryMock) TotalCostAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTotalCost.afterTotalCostCounter)
}

// TotalCostBeforeCounter returns a count of SubscriptionRepositoryMock.TotalCost invocations
func (mmTotalCost *SubscriptionRepositoryMock) TotalCostBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTotalCost.beforeTotalCostCounter)
}

// Calls returns a list of arguments used in each call to SubscriptionRepositoryMock.TotalCost.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmTotalCost *mSubscriptionRepositoryMockTotalCost) Calls() []*SubscriptionRepositoryMockTotalCostParams {
	mmTotalCost.mutex.RLock()

	argCopy := make([]*SubscriptionRepositoryMockTotalCostParams, len(mmTotalCost.callArgs))
	copy(argCopy, mmTotalCost.callArgs)

	mmTotalCost.mutex.RUnlock()

	return argCopy
}

// MinimockTotalCostDone returns true if the count of the TotalCost invocations corresponds
// the number of defined expectations
func (m *SubscriptionRepositoryMock) MinimockTotalCostDone() bool {
	if m.TotalCostMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.TotalCostMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.TotalCostMock.invocationsDone()
}

// MinimockTotalCostInspect logs each unmet expectation
func (m *SubscriptionRepositoryMock) MinimockTotalCostInspect() {
	for _, e := range m.TotalCostMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.TotalCost at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterTotalCostCounter := mm_atomic.LoadUint64(&m.afterTotalCostCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.TotalCostMock.defaultExpectation != nil && afterTotalCostCounter < 1 {
		if m.TotalCostMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.TotalCost at\n%s", m.TotalCostMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.TotalCost at\n%s with params: %#v", m.TotalCostMock.defaultExpectation.expectationOrigins.origin, *m.TotalCostMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcTotalCost != nil && afterTotalCostCounter < 1 {
		m.t.Errorf("Expected call to SubscriptionRepositoryMock.TotalCost at\n%s", m.funcTotalCostOrigin)
	}

	if !m.TotalCostMock.invocationsDone() && afterTotalCostCounter > 0 {
		m.t.Errorf("Expected %d calls to SubscriptionRepositoryMock.TotalCost at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.TotalCostMock.expectedInvocations), m.TotalCostMock.expectedInvocationsOrigin, afterTotalCostCounter)
	}
}

type mSubscriptionRepositoryMockUpdate struct {
	optional           bool
	mock               *SubscriptionRepositoryMock
	defaultExpectation *SubscriptionRepositoryMockUpdateExpectation
	expectations       []*SubscriptionRepositoryMockUpdateExpectation

	callArgs []*SubscriptionRepositoryMockUpdateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SubscriptionRepositoryMockUpdateExpectation specifies expectation struct of the SubscriptionRepository.Update
type SubscriptionRepositoryMockUpdateExpectation struct {
	mock               *SubscriptionRepositoryMock
	params             *SubscriptionRepositoryMockUpdateParams
	paramPtrs          *SubscriptionRepositoryMockUpdateParamPtrs
	expectationOrigins SubscriptionRepositoryMockUpdateExpectationOrigins
	results            *SubscriptionRepositoryMockUpdateResults
	returnOrigin       string
	Counter            uint64
}

// SubscriptionRepositoryMockUpdateParams contains parameters of the SubscriptionRepository.Update
type SubscriptionRepositoryMockUpdateParams struct {
	ctx context.Context
	sub *domain.Subscription
}

// SubscriptionRepositoryMockUpdateParamPtrs contains pointers to parameters of the SubscriptionRepository.Update
type SubscriptionRepositoryMockUpdateParamPtrs struct {
	ctx *context.Context
	sub **domain.Subscription
}

// SubscriptionRepositoryMockUpdateResults contains results of the SubscriptionRepository.Update
type SubscriptionRepositoryMockUpdateResults struct {
	sp1 *domain.Subscription
	err error
}

// SubscriptionRepositoryMockUpdateOrigins contains origins of expectations of the SubscriptionRepository.Update
type SubscriptionRepositoryMockUpdateExpectationOrigins struct {
	origin    string
	originCtx string
	originSub string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdate *mSubscriptionRepositoryMockUpdate) Optional() *mSubscriptionRepositoryMockUpdate {
	mmUpdate.optional = true
	return mmUpdate
}

// Expect sets up expected params for SubscriptionRepository.Update
func (mmUpdate *mSubscriptionRepositoryMockUpdate) Expect(ctx context.Context, sub *domain.Subscription) *mSubscriptionRepositoryMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionRepositoryMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &SubscriptionRepositoryMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.paramPtrs != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionRepositoryMock.Update mock is already set by ExpectParams functions")
	}

	mmUpdate.defaultExpectation.params = &SubscriptionRepositoryMockUpdateParams{ctx, sub}
	mmUpdate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdate.expectations {
		if minimock.Equal(e.params, mmUpdate.defaultExpectation.params) {
			mmUpdate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdate.defaultExpectation.params)
		}
	}

	return mmUpdate
}

// ExpectCtxParam1 sets up expected param ctx for SubscriptionRepository.Update
func (mmUpdate *mSubscriptionRepositoryMockUpdate) ExpectCtxParam1(ctx context.Context) *mSubscriptionRepositoryMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionRepositoryMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &SubscriptionRepositoryMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.params != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionRepositoryMock.Update mock is already set by Expect")
	}

	if mmUpdate.defaultExpectation.paramPtrs == nil {
		mmUpdate.defaultExpectation.paramPtrs = &SubscriptionRepositoryMockUpdateParamPtrs{}
	}
	mmUpdate.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdate
}

// ExpectSubParam2 sets up expected param sub for SubscriptionRepository.Update
func (mmUpdate *mSubscriptionRepositoryMockUpdate) ExpectSubParam2(sub *domain.Subscription) *mSubscriptionRepositoryMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionRepositoryMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &SubscriptionRepositoryMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.params != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionRepositoryMock.Update mock is already set by Expect")
	}

	if mmUpdate.defaultExpectation.paramPtrs == nil {
		mmUpdate.defaultExpectation.paramPtrs = &SubscriptionRepositoryMockUpdateParamPtrs{}
	}
	mmUpdate.defaultExpectation.paramPtrs.sub = &sub
	mmUpdate.defaultExpectation.expectationOrigins.originSub = minimock.CallerInfo(1)

	return mmUpdate
}

// Inspect accepts an inspector function that has same arguments as the SubscriptionRepository.Update
func (mmUpdate *mSubscriptionRepositoryMockUpdate) Inspect(f func(ctx context.Context, sub *domain.Subscription)) *mSubscriptionRepositoryMockUpdate {
	if mmUpdate.mock.inspectFuncUpdate != nil {
		mmUpdate.mock.t.Fatalf("Inspect function is already set for SubscriptionRepositoryMock.Update")
	}

	mmUpdate.mock.inspectFuncUpdate = f

	return mmUpdate
}

// Return sets up results that will be returned by SubscriptionRepository.Update
func (mmUpdate *mSubscriptionRepositoryMockUpdate) Return(sp1 *domain.Subscription, err error) *SubscriptionRepositoryMock {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionRepositoryMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &SubscriptionRepositoryMockUpdateExpectation{mock: mmUpdate.mock}
	}
	mmUpdate.defaultExpectation.results = &SubscriptionRepositoryMockUpdateResults{sp1, err}
	mmUpdate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdate.mock
}

// Set uses given function f to mock the SubscriptionRepository.Update method
func (mmUpdate *mSubscriptionRepositoryMockUpdate) Set(f func(ctx context.Context, sub *domain.Subscription) (sp1 *domain.Subscription, err error)) *SubscriptionRepositoryMock {
	if mmUpdate.defaultExpectation != nil {
		mmUpdate.mock.t.Fatalf("Default expectation is already set for the SubscriptionRepository.Update method")
	}

	if len(mmUpdate.expectations) > 0 {
		mmUpdate.mock.t.Fatalf("Some expectations are already set for the SubscriptionRepository.Update method")
	}

	mmUpdate.mock.funcUpdate = f
	mmUpdate.mock.funcUpdateOrigin = minimock.CallerInfo(1)
	return mmUpdate.mock
}

// When sets expectation for the SubscriptionRepository.Update which will trigger the result defined by the following
// Then helper
func (mmUpdate *mSubscriptionRepositoryMockUpdate) When(ctx context.Context, sub *domain.Subscription) *SubscriptionRepositoryMockUpdateExpectation {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionRepositoryMock.Update mock is already set by Set")
	}

	expectation := &SubscriptionRepositoryMockUpdateExpectation{
		mock:               mmUpdate.mock,
		params:             &SubscriptionRepositoryMockUpdateParams{ctx, sub},
		expectationOrigins: SubscriptionRepositoryMockUpdateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdate.expectations = append(mmUpdate.expectations, expectation)
	return expectation
}

// Then sets up SubscriptionRepository.Update return parameters for the expectation previously defined by the When method
func (e *SubscriptionRepositoryMockUpdateExpectation) Then(sp1 *domain.Subscription, err error) *SubscriptionRepositoryMock {
	e.results = &SubscriptionRepositoryMockUpdateResults{sp1, err}
	return e.mock
}

// Times sets number of times SubscriptionRepository.Update should be invoked
func (mmUpdate *mSubscriptionRepositoryMockUpdate) Times(n uint64) *mSubscriptionRepositoryMockUpdate {
	if n == 0 {
		mmUpdate.mock.t.Fatalf("Times of SubscriptionRepositoryMock.Update mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdate.expectedInvocations, n)
	mmUpdate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdate
}

func (mmUpdate *mSubscriptionRepositoryMockUpdate) invocationsDone() bool {
	if len(mmUpdate.expectations) == 0 && mmUpdate.defaultExpectation == nil && mmUpdate.mock.funcUpdate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdate.mock.afterUpdateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Update implements mm_repository.SubscriptionRepository
func (mmUpdate *SubscriptionRepositoryMock) Update(ctx context.Context, sub *domain.Subscription) (sp1 *domain.Subscription, err error) {
	mm_atomic.AddUint64(&mmUpdate.beforeUpdateCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdate.afterUpdateCounter, 1)

	mmUpdate.t.Helper()

	if mmUpdate.inspectFuncUpdate != nil {
		mmUpdate.inspectFuncUpdate(ctx, sub)
	}

	mm_params := SubscriptionRepositoryMockUpdateParams{ctx, sub}

	// Record call args
	mmUpdate.UpdateMock.mutex.Lock()
	mmUpdate.UpdateMock.callArgs = append(mmUpdate.UpdateMock.callArgs, &mm_params)
	mmUpdate.UpdateMock.mutex.Unlock()

	for _, e := range mmUpdate.UpdateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmUpdate.UpdateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdate.UpdateMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdate.UpdateMock.defaultExpectation.params
		mm_want_ptrs := mmUpdate.UpdateMock.defaultExpectation.paramPtrs

		mm_got := SubscriptionRepositoryMockUpdateParams{ctx, sub}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdate.t.Errorf("SubscriptionRepositoryMock.Update got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sub != nil && !minimock.Equal(*mm_want_ptrs.sub, mm_got.sub) {
				mmUpdate.t.Errorf("SubscriptionRepositoryMock.Update got unexpected parameter sub, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.originSub, *mm_want_ptrs.sub, mm_got.sub, minimock.Diff(*mm_want_ptrs.sub, mm_got.sub))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdate.t.Errorf("SubscriptionRepositoryMock.Update got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdate.UpdateMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdate.t.Fatal("No results are set for the SubscriptionRepositoryMock.Update")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmUpdate.funcUpdate != nil {
		return mmUpdate.funcUpdate(ctx, sub)
	}
	mmUpdate.t.Fatalf("Unexpected call to SubscriptionRepositoryMock.Update. %v %v", ctx, sub)
	return
}

// UpdateAfterCounter returns a count of finished SubscriptionRepositoryMock.Update invocations
func (mmUpdate *SubscriptionRepositoryMock) UpdateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdate.afterUpdateCounter)
}

// UpdateBeforeCounter returns a count of SubscriptionRepositoryMock.Update invocations
func (mmUpdate *SubscriptionRepositoryMock) UpdateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdate.beforeUpdateCounter)
}

// Calls returns a list of arguments used in each call to SubscriptionRepositoryMock.Update.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdate *mSubscriptionRepositoryMockUpdate) Calls() []*SubscriptionRepositoryMockUpdateParams {
	mmUpdate.mutex.RLock()

	argCopy := make([]*SubscriptionRepositoryMockUpdateParams, len(mmUpdate.callArgs))
	copy(argCopy, mmUpdate.callArgs)

	mmUpdate.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateDone returns true if the count of the Update invocations corresponds
// the number of defined expectations
func (m *SubscriptionRepositoryMock) MinimockUpdateDone() bool {
	if m.UpdateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateMock.invocationsDone()
}

// MinimockUpdateInspect logs each unmet expectation
func (m *SubscriptionRepositoryMock) MinimockUpdateInspect() {
	for _, e := range m.UpdateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.Update at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateCounter := mm_atomic.LoadUint64(&m.afterUpdateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateMock.defaultExpectation != nil && afterUpdateCounter < 1 {
		if m.UpdateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.Update at\n%s", m.UpdateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SubscriptionRepositoryMock.Update at\n%s with params: %#v", m.UpdateMock.defaultExpectation.expectationOrigins.origin, *m.UpdateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdate != nil && afterUpdateCounter < 1 {
		m.t.Errorf("Expected call to SubscriptionRepositoryMock.Update at\n%s", m.funcUpdateOrigin)
	}

	if !m.UpdateMock.invocationsDone() && afterUpdateCounter > 0 {
		m.t.Errorf("Expected %d calls to SubscriptionRepositoryMock.Update at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateMock.expectedInvocations), m.UpdateMock.expectedInvocationsOrigin, afterUpdateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *SubscriptionRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockDeleteInspect()

			m.MinimockGetAllInspect()

			m.MinimockGetByIDInspect()

			m.MinimockTotalCostInspect()

			m.MinimockUpdateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *SubscriptionRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *SubscriptionRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockDeleteDone() &&
		m.MinimockGetAllDone() &&
		m.MinimockGetByIDDone() &&
		m.MinimockTotalCostDone() &&
		m.MinimockUpdateDone()
}
