// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/RSODA/subscribe-manager/internal/service.SubscriptionService -o subscription_service_minimock.go -n SubscriptionServiceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	"time"
	mm_time "time"

	"github.com/RSODA/subscribe-manager/internal/domain"
	"github.com/gojuno/minimock/v3"
)

// SubscriptionServiceMock implements mm_service.SubscriptionService
type SubscriptionServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, sub *domain.Subscription) (sp1 *domain.Subscription, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, sub *domain.Subscription)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mSubscriptionServiceMockCreate

	funcDelete          func(ctx context.Context, id string) (err error)
	funcDeleteOrigin    string
	inspectFuncDelete   func(ctx context.Context, id string)
	afterDeleteCounter  uint64
	beforeDeleteCounter uint64
	DeleteMock          mSubscriptionServiceMockDelete

	funcGetAll          func(ctx context.Context) (spa1 []*domain.Subscription, err error)
	funcGetAllOrigin    string
	inspectFuncGetAll   func(ctx context.Context)
	afterGetAllCounter  uint64
	beforeGetAllCounter uint64
	GetAllMock          mSubscriptionServiceMockGetAll

	funcGetByID          func(ctx context.Context, id string) (sp1 *domain.Subscription, err error)
	funcGetByIDOrigin    string
	inspectFuncGetByID   func(ctx context.Context, id string)
	afterGetByIDCounter  uint64
	beforeGetByIDCounter uint64
	GetByIDMock          mSubscriptionServiceMockGetByID

	funcTotalCost          func(ctx context.Context, userID *string, serviceName *string, from *time.Time, to *time.Time) (i1 int, err error)
	funcTotalCostOrigin    string
	inspectFuncTotalCost   func(ctx context.Context, userID *string, serviceName *string, from *time.Time, to *time.Time)
	afterTotalCostCounter  uint64
	beforeTotalCostCounter uint64
	TotalCostMock          mSubscriptionServiceMockTotalCost

	funcUpdate          func(ctx context.Context, sub *domain.Subscription) (sp1 *domain.Subscription, err error)
	funcUpdateOrigin    string
	inspectFuncUpdate   func(ctx context.Context, sub *domain.Subscription)
	afterUpdateCounter  uint64
	beforeUpdateCounter uint64
	UpdateMock          mSubscriptionServiceMockUpdate
}

// NewSubscriptionServiceMock returns a mock for mm_service.SubscriptionService
func NewSubscriptionServiceMock(t minimock.Tester) *SubscriptionServiceMock {
	m := &SubscriptionServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mSubscriptionServiceMockCreate{mock: m}
	m.CreateMock.callArgs = []*SubscriptionServiceMockCreateParams{}

	m.DeleteMock = mSubscriptionServiceMockDelete{mock: m}
	m.DeleteMock.callArgs = []*SubscriptionServiceMockDeleteParams{}

	m.GetAllMock = mSubscriptionServiceMockGetAll{mock: m}
	m.GetAllMock.callArgs = []*SubscriptionServiceMockGetAllParams{}

	m.GetByIDMock = mSubscriptionServiceMockGetByID{mock: m}
	m.GetByIDMock.callArgs = []*SubscriptionServiceMockGetByIDParams{}

	m.TotalCostMock = mSubscriptionServiceMockTotalCost{mock: m}
	m.TotalCostMock.callArgs = []*SubscriptionServiceMockTotalCostParams{}

	m.UpdateMock = mSubscriptionServiceMockUpdate{mock: m}
	m.UpdateMock.callArgs = []*SubscriptionServiceMockUpdateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mSubscriptionServiceMockCreate struct {
	optional           bool
	mock               *SubscriptionServiceMock
	defaultExpectation *SubscriptionServiceMockCreateExpectation
	expectations       []*SubscriptionServiceMockCreateExpectation

	callArgs []*SubscriptionServiceMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SubscriptionServiceMockCreateExpectation specifies expectation struct of the SubscriptionService.Create
type SubscriptionServiceMockCreateExpectation struct {
	mock               *SubscriptionServiceMock
	params             *SubscriptionServiceMockCreateParams
	paramPtrs          *SubscriptionServiceMockCreateParamPtrs
	expectationOrigins SubscriptionServiceMockCreateExpectationOrigins
	results            *SubscriptionServiceMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// SubscriptionServiceMockCreateParams contains parameters of the SubscriptionService.Create
type SubscriptionServiceMockCreateParams struct {
	ctx context.Context
	sub *domain.Subscription
}

// SubscriptionServiceMockCreateParamPtrs contains pointers to parameters of the SubscriptionService.Create
type SubscriptionServiceMockCreateParamPtrs struct {
	ctx *context.Context
	sub **domain.Subscription
}

// SubscriptionServiceMockCreateResults contains results of the SubscriptionService.Create
type SubscriptionServiceMockCreateResults struct {
	sp1 *domain.Subscription
	err error
}

// SubscriptionServiceMockCreateOrigins contains origins of expectations of the SubscriptionService.Create
type SubscriptionServiceMockCreateExpectationOrigins struct {
	origin    string
	originCtx string
	originSub string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mSubscriptionServiceMockCreate) Optional() *mSubscriptionServiceMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for SubscriptionService.Create
func (mmCreate *mSubscriptionServiceMockCreate) Expect(ctx context.Context, sub *domain.Subscription) *mSubscriptionServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("SubscriptionServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &SubscriptionServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("SubscriptionServiceMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &SubscriptionServiceMockCreateParams{ctx, sub}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for SubscriptionService.Create
func (mmCreate *mSubscriptionServiceMockCreate) ExpectCtxParam1(ctx context.Context) *mSubscriptionServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("SubscriptionServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &SubscriptionServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("SubscriptionServiceMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &SubscriptionServiceMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectSubParam2 sets up expected param sub for SubscriptionService.Create
func (mmCreate *mSubscriptionServiceMockCreate) ExpectSubParam2(sub *domain.Subscription) *mSubscriptionServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("SubscriptionServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &SubscriptionServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("SubscriptionServiceMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &SubscriptionServiceMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.sub = &sub
	mmCreate.defaultExpectation.expectationOrigins.originSub = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the SubscriptionService.Create
func (mmCreate *mSubscriptionServiceMockCreate) Inspect(f func(ctx context.Context, sub *domain.Subscription)) *mSubscriptionServiceMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for SubscriptionServiceMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by SubscriptionService.Create
func (mmCreate *mSubscriptionServiceMockCreate) Return(sp1 *domain.Subscription, err error) *SubscriptionServiceMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("SubscriptionServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &SubscriptionServiceMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &SubscriptionServiceMockCreateResults{sp1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the SubscriptionService.Create method
func (mmCreate *mSubscriptionServiceMockCreate) Set(f func(ctx context.Context, sub *domain.Subscription) (sp1 *domain.Subscription, err error)) *SubscriptionServiceMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the SubscriptionService.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the SubscriptionService.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the SubscriptionService.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mSubscriptionServiceMockCreate) When(ctx context.Context, sub *domain.Subscription) *SubscriptionServiceMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("SubscriptionServiceMock.Create mock is already set by Set")
	}

	expectation := &SubscriptionServiceMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &SubscriptionServiceMockCreateParams{ctx, sub},
		expectationOrigins: SubscriptionServiceMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up SubscriptionService.Create return parameters for the expectation previously defined by the When method
func (e *SubscriptionServiceMockCreateExpectation) Then(sp1 *domain.Subscription, err error) *SubscriptionServiceMock {
	e.results = &SubscriptionServiceMockCreateResults{sp1, err}
	return e.mock
}

// Times sets number of times SubscriptionService.Create should be invoked
func (mmCreate *mSubscriptionServiceMockCreate) Times(n uint64) *mSubscriptionServiceMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of SubscriptionServiceMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mSubscriptionServiceMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_service.SubscriptionService
func (mmCreate *SubscriptionServiceMock) Create(ctx context.Context, sub *domain.Subscription) (sp1 *domain.Subscription, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, sub)
	}

	mm_params := SubscriptionServiceMockCreateParams{ctx, sub}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := SubscriptionServiceMockCreateParams{ctx, sub}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("SubscriptionServiceMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sub != nil && !minimock.Equal(*mm_want_ptrs.sub, mm_got.sub) {
				mmCreate.t.Errorf("SubscriptionServiceMock.Create got unexpected parameter sub, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originSub, *mm_want_ptrs.sub, mm_got.sub, minimock.Diff(*mm_want_ptrs.sub, mm_got.sub))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("SubscriptionServiceMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the SubscriptionServiceMock.Create")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, sub)
	}
	mmCreate.t.Fatalf("Unexpected call to SubscriptionServiceMock.Create. %v %v", ctx, sub)
	return
}

// CreateAfterCounter returns a count of finished SubscriptionServiceMock.Create invocations
func (mmCreate *SubscriptionServiceMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of SubscriptionServiceMock.Create invocations
func (mmCreate *SubscriptionServiceMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to SubscriptionServiceMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mSubscriptionServiceMockCreate) Calls() []*SubscriptionServiceMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*SubscriptionServiceMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *SubscriptionServiceMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *SubscriptionServiceMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SubscriptionServiceMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SubscriptionServiceMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SubscriptionServiceMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to SubscriptionServiceMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to SubscriptionServiceMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mSubscriptionServiceMockDelete struct {
	optional           bool
	mock               *SubscriptionServiceMock
	defaultExpectation *SubscriptionServiceMockDeleteExpectation
	expectations       []*SubscriptionServiceMockDeleteExpectation

	callArgs []*SubscriptionServiceMockDeleteParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SubscriptionServiceMockDeleteExpectation specifies expectation struct of the SubscriptionService.Delete
type SubscriptionServiceMockDeleteExpectation struct {
	mock               *SubscriptionServiceMock
	params             *SubscriptionServiceMockDeleteParams
	paramPtrs          *SubscriptionServiceMockDeleteParamPtrs
	expectationOrigins SubscriptionServiceMockDeleteExpectationOrigins
	results            *SubscriptionServiceMockDeleteResults
	returnOrigin       string
	Counter            uint64
}

// SubscriptionServiceMockDeleteParams contains parameters of the SubscriptionService.Delete
type SubscriptionServiceMockDeleteParams struct {
	ctx context.Context
	id  string
}

// SubscriptionServiceMockDeleteParamPtrs contains pointers to parameters of the SubscriptionService.Delete
type SubscriptionServiceMockDeleteParamPtrs struct {
	ctx *context.Context
	id  *string
}

// SubscriptionServiceMockDeleteResults contains results of the SubscriptionService.Delete
type SubscriptionServiceMockDeleteResults struct {
	err error
}

// SubscriptionServiceMockDeleteOrigins contains origins of expectations of the SubscriptionService.Delete
type SubscriptionServiceMockDeleteExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDelete *mSubscriptionServiceMockDelete) Optional() *mSubscriptionServiceMockDelete {
	mmDelete.optional = true
	return mmDelete
}

// Expect sets up expected params for SubscriptionService.Delete
func (mmDelete *mSubscriptionServiceMockDelete) Expect(ctx context.Context, id string) *mSubscriptionServiceMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("SubscriptionServiceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &SubscriptionServiceMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.paramPtrs != nil {
		mmDelete.mock.t.Fatalf("SubscriptionServiceMock.Delete mock is already set by ExpectParams functions")
	}

	mmDelete.defaultExpectation.params = &SubscriptionServiceMockDeleteParams{ctx, id}
	mmDelete.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDelete.expectations {
		if minimock.Equal(e.params, mmDelete.defaultExpectation.params) {
			mmDelete.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDelete.defaultExpectation.params)
		}
	}

	return mmDelete
}

// ExpectCtxParam1 sets up expected param ctx for SubscriptionService.Delete
func (mmDelete *mSubscriptionServiceMockDelete) ExpectCtxParam1(ctx context.Context) *mSubscriptionServiceMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("SubscriptionServiceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &SubscriptionServiceMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("SubscriptionServiceMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &SubscriptionServiceMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.ctx = &ctx
	mmDelete.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectIdParam2 sets up expected param id for SubscriptionService.Delete
func (mmDelete *mSubscriptionServiceMockDelete) ExpectIdParam2(id string) *mSubscriptionServiceMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("SubscriptionServiceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &SubscriptionServiceMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("SubscriptionServiceMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &SubscriptionServiceMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.id = &id
	mmDelete.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmDelete
}

// Inspect accepts an inspector function that has same arguments as the SubscriptionService.Delete
func (mmDelete *mSubscriptionServiceMockDelete) Inspect(f func(ctx context.Context, id string)) *mSubscriptionServiceMockDelete {
	if mmDelete.mock.inspectFuncDelete != nil {
		mmDelete.mock.t.Fatalf("Inspect function is already set for SubscriptionServiceMock.Delete")
	}

	mmDelete.mock.inspectFuncDelete = f

	return mmDelete
}

// Return sets up results that will be returned by SubscriptionService.Delete
func (mmDelete *mSubscriptionServiceMockDelete) Return(err error) *SubscriptionServiceMock {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("SubscriptionServiceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &SubscriptionServiceMockDeleteExpectation{mock: mmDelete.mock}
	}
	mmDelete.defaultExpectation.results = &SubscriptionServiceMockDeleteResults{err}
	mmDelete.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// Set uses given function f to mock the SubscriptionService.Delete method
func (mmDelete *mSubscriptionServiceMockDelete) Set(f func(ctx context.Context, id string) (err error)) *SubscriptionServiceMock {
	if mmDelete.defaultExpectation != nil {
		mmDelete.mock.t.Fatalf("Default expectation is already set for the SubscriptionService.Delete method")
	}

	if len(mmDelete.expectations) > 0 {
		mmDelete.mock.t.Fatalf("Some expectations are already set for the SubscriptionService.Delete method")
	}

	mmDelete.mock.funcDelete = f
	mmDelete.mock.funcDeleteOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// When sets expectation for the SubscriptionService.Delete which will trigger the result defined by the following
// Then helper
func (mmDelete *mSubscriptionServiceMockDelete) When(ctx context.Context, id string) *SubscriptionServiceMockDeleteExpectation {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("SubscriptionServiceMock.Delete mock is already set by Set")
	}

	expectation := &SubscriptionServiceMockDeleteExpectation{
		mock:               mmDelete.mock,
		params:             &SubscriptionServiceMockDeleteParams{ctx, id},
		expectationOrigins: SubscriptionServiceMockDeleteExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDelete.expectations = append(mmDelete.expectations, expectation)
	return expectation
}

// Then sets up SubscriptionService.Delete return parameters for the expectation previously defined by the When method
func (e *SubscriptionServiceMockDeleteExpectation) Then(err error) *SubscriptionServiceMock {
	e.results = &SubscriptionServiceMockDeleteResults{err}
	return e.mock
}

// Times sets number of times SubscriptionService.Delete should be invoked
func (mmDelete *mSubscriptionServiceMockDelete) Times(n uint64) *mSubscriptionServiceMockDelete {
	if n == 0 {
		mmDelete.mock.t.Fatalf("Times of SubscriptionServiceMock.Delete mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDelete.expectedInvocations, n)
	mmDelete.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDelete
}

func (mmDelete *mSubscriptionServiceMockDelete) invocationsDone() bool {
	if len(mmDelete.expectations) == 0 && mmDelete.defaultExpectation == nil && mmDelete.mock.funcDelete == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDelete.mock.afterDeleteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDelete.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Delete implements mm_service.SubscriptionService
func (mmDelete *SubscriptionServiceMock) Delete(ctx context.Context, id string) (err error) {
	mm_atomic.AddUint64(&mmDelete.beforeDeleteCounter, 1)
	defer mm_atomic.AddUint64(&mmDelete.afterDeleteCounter, 1)

	mmDelete.t.Helper()

	if mmDelete.inspectFuncDelete != nil {
		mmDelete.inspectFuncDelete(ctx, id)
	}

	mm_params := SubscriptionServiceMockDeleteParams{ctx, id}

	// Record call args
	mmDelete.DeleteMock.mutex.Lock()
	mmDelete.DeleteMock.callArgs = append(mmDelete.DeleteMock.callArgs, &mm_params)
	mmDelete.DeleteMock.mutex.Unlock()

	for _, e := range mmDelete.DeleteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDelete.DeleteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDelete.DeleteMock.defaultExpectation.Counter, 1)
		mm_want := mmDelete.DeleteMock.defaultExpectation.params
		mm_want_ptrs := mmDelete.DeleteMock.defaultExpectation.paramPtrs

		mm_got := SubscriptionServiceMockDeleteParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDelete.t.Errorf("SubscriptionServiceMock.Delete got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmDelete.t.Errorf("SubscriptionServiceMock.Delete got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDelete.t.Errorf("SubscriptionServiceMock.Delete got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDelete.DeleteMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDelete.DeleteMock.defaultExpectation.results
		if mm_results == nil {
			mmDelete.t.Fatal("No results are set for the SubscriptionServiceMock.Delete")
		}
		return (*mm_results).err
	}
	if mmDelete.funcDelete != nil {
		return mmDelete.funcDelete(ctx, id)
	}
	mmDelete.t.Fatalf("Unexpected call to SubscriptionServiceMock.Delete. %v %v", ctx, id)
	return
}

// DeleteAfterCounter returns a count of finished SubscriptionServiceMock.Delete invocations
func (mmDelete *SubscriptionServiceMock) DeleteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.afterDeleteCounter)
}

// DeleteBeforeCounter returns a count of SubscriptionServiceMock.Delete invocations
func (mmDelete *SubscriptionServiceMock) DeleteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.beforeDeleteCounter)
}

// Calls returns a list of arguments used in each call to SubscriptionServiceMock.Delete.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDelete *mSubscriptionServiceMockDelete) Calls() []*SubscriptionServiceMockDeleteParams {
	mmDelete.mutex.RLock()

	argCopy := make([]*SubscriptionServiceMockDeleteParams, len(mmDelete.callArgs))
	copy(argCopy, mmDelete.callArgs)

	mmDelete.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteDone returns true if the count of the Delete invocations corresponds
// the number of defined expectations
func (m *SubscriptionServiceMock) MinimockDeleteDone() bool {
	if m.DeleteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteMock.invocationsDone()
}

// MinimockDeleteInspect logs each unmet expectation
func (m *SubscriptionServiceMock) MinimockDeleteInspect() {
	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SubscriptionServiceMock.Delete at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteCounter := mm_atomic.LoadUint64(&m.afterDeleteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteMock.defaultExpectation != nil && afterDeleteCounter < 1 {
		if m.DeleteMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SubscriptionServiceMock.Delete at\n%s", m.DeleteMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SubscriptionServiceMock.Delete at\n%s with params: %#v", m.DeleteMock.defaultExpectation.expectationOrigins.origin, *m.DeleteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDelete != nil && afterDeleteCounter < 1 {
		m.t.Errorf("Expected call to SubscriptionServiceMock.Delete at\n%s", m.funcDeleteOrigin)
	}

	if !m.DeleteMock.invocationsDone() && afterDeleteCounter > 0 {
		m.t.Errorf("Expected %d calls to SubscriptionServiceMock.Delete at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteMock.expectedInvocations), m.DeleteMock.expectedInvocationsOrigin, afterDeleteCounter)
	}
}

type mSubscriptionServiceMockGetAll struct {
	optional           bool
	mock               *SubscriptionServiceMock
	defaultExpectation *SubscriptionServiceMockGetAllExpectation
	expectations       []*SubscriptionServiceMockGetAllExpectation

	callArgs []*SubscriptionServiceMockGetAllParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SubscriptionServiceMockGetAllExpectation specifies expectation struct of the SubscriptionService.GetAll
type SubscriptionServiceMockGetAllExpectation struct {
	mock               *SubscriptionServiceMock
	params             *SubscriptionServiceMockGetAllParams
	paramPtrs          *SubscriptionServiceMockGetAllParamPtrs
	expectationOrigins SubscriptionServiceMockGetAllExpectationOrigins
	results            *SubscriptionServiceMockGetAllResults
	returnOrigin       string
	Counter            uint64
}

// SubscriptionServiceMockGetAllParams contains parameters of the SubscriptionService.GetAll
type SubscriptionServiceMockGetAllParams struct {
	ctx context.Context
}

// SubscriptionServiceMockGetAllParamPtrs contains pointers to parameters of the SubscriptionService.GetAll
type SubscriptionServiceMockGetAllParamPtrs struct {
	ctx *context.Context
}

// SubscriptionServiceMockGetAllResults contains results of the SubscriptionService.GetAll
type SubscriptionServiceMockGetAllResults struct {
	spa1 []*domain.Subscription
	err  error
}

// SubscriptionServiceMockGetAllOrigins contains origins of expectations of the SubscriptionService.GetAll
type SubscriptionServiceMockGetAllExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetAll *mSubscriptionServiceMockGetAll) Optional() *mSubscriptionServiceMockGetAll {
	mmGetAll.optional = true
	return mmGetAll
}

// Expect sets up expected params for SubscriptionService.GetAll
func (mmGetAll *mSubscriptionServiceMockGetAll) Expect(ctx context.Context) *mSubscriptionServiceMockGetAll {
	if mmGetAll.mock.funcGetAll != nil {
		mmGetAll.mock.t.Fatalf("SubscriptionServiceMock.GetAll mock is already set by Set")
	}

	if mmGetAll.defaultExpectation == nil {
		mmGetAll.defaultExpectation = &SubscriptionServiceMockGetAllExpectation{}
	}

	if mmGetAll.defaultExpectation.paramPtrs != nil {
		mmGetAll.mock.t.Fatalf("SubscriptionServiceMock.GetAll mock is already set by ExpectParams functions")
	}

	mmGetAll.defaultExpectation.params = &SubscriptionServiceMockGetAllParams{ctx}
	mmGetAll.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetAll.expectations {
		if minimock.Equal(e.params, mmGetAll.defaultExpectation.params) {
			mmGetAll.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetAll.defaultExpectation.params)
		}
	}

	return mmGetAll
}

// ExpectCtxParam1 sets up expected param ctx for SubscriptionService.GetAll
func (mmGetAll *mSubscriptionServiceMockGetAll) ExpectCtxParam1(ctx context.Context) *mSubscriptionServiceMockGetAll {
	if mmGetAll.mock.funcGetAll != nil {
		mmGetAll.mock.t.Fatalf("SubscriptionServiceMock.GetAll mock is already set by Set")
	}

	if mmGetAll.defaultExpectation == nil {
		mmGetAll.defaultExpectation = &SubscriptionServiceMockGetAllExpectation{}
	}

	if mmGetAll.defaultExpectation.params != nil {
		mmGetAll.mock.t.Fatalf("SubscriptionServiceMock.GetAll mock is already set by Expect")
	}

	if mmGetAll.defaultExpectation.paramPtrs == nil {
		mmGetAll.defaultExpectation.paramPtrs = &SubscriptionServiceMockGetAllParamPtrs{}
	}
	mmGetAll.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetAll.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetAll
}

// Inspect accepts an inspector function that has same arguments as the SubscriptionService.GetAll
func (mmGetAll *mSubscriptionServiceMockGetAll) Inspect(f func(ctx context.Context)) *mSubscriptionServiceMockGetAll {
	if mmGetAll.mock.inspectFuncGetAll != nil {
		mmGetAll.mock.t.Fatalf("Inspect function is already set for SubscriptionServiceMock.GetAll")
	}

	mmGetAll.mock.inspectFuncGetAll = f

	return mmGetAll
}

// Return sets up results that will be returned by SubscriptionService.GetAll
func (mmGetAll *mSubscriptionServiceMockGetAll) Return(spa1 []*domain.Subscription, err error) *SubscriptionServiceMock {
	if mmGetAll.mock.funcGetAll != nil {
		mmGetAll.mock.t.Fatalf("SubscriptionServiceMock.GetAll mock is already set by Set")
	}

	if mmGetAll.defaultExpectation == nil {
		mmGetAll.defaultExpectation = &SubscriptionServiceMockGetAllExpectation{mock: mmGetAll.mock}
	}
	mmGetAll.defaultExpectation.results = &SubscriptionServiceMockGetAllResults{spa1, err}
	mmGetAll.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetAll.mock
}

// Set uses given function f to mock the SubscriptionService.GetAll method
func (mmGetAll *mSubscriptionServiceMockGetAll) Set(f func(ctx context.Context) (spa1 []*domain.Subscription, err error)) *SubscriptionServiceMock {
	if mmGetAll.defaultExpectation != nil {
		mmGetAll.mock.t.Fatalf("Default expectation is already set for the SubscriptionService.GetAll method")
	}

	if len(mmGetAll.expectations) > 0 {
		mmGetAll.mock.t.Fatalf("Some expectations are already set for the SubscriptionService.GetAll method")
	}

	mmGetAll.mock.funcGetAll = f
	mmGetAll.mock.funcGetAllOrigin = minimock.CallerInfo(1)
	return mmGetAll.mock
}

// When sets expectation for the SubscriptionService.GetAll which will trigger the result defined by the following
// Then helper
func (mmGetAll *mSubscriptionServiceMockGetAll) When(ctx context.Context) *SubscriptionServiceMockGetAllExpectation {
	if mmGetAll.mock.funcGetAll != nil {
		mmGetAll.mock.t.Fatalf("SubscriptionServiceMock.GetAll mock is already set by Set")
	}

	expectation := &SubscriptionServiceMockGetAllExpectation{
		mock:               mmGetAll.mock,
		params:             &SubscriptionServiceMockGetAllParams{ctx},
		expectationOrigins: SubscriptionServiceMockGetAllExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetAll.expectations = append(mmGetAll.expectations, expectation)
	return expectation
}

// Then sets up SubscriptionService.GetAll return parameters for the expectation previously defined by the When method
func (e *SubscriptionServiceMockGetAllExpectation) Then(spa1 []*domain.Subscription, err error) *SubscriptionServiceMock {
	e.results = &SubscriptionServiceMockGetAllResults{spa1, err}
	return e.mock
}

// Times sets number of times SubscriptionService.GetAll should be invoked
func (mmGetAll *mSubscriptionServiceMockGetAll) Times(n uint64) *mSubscriptionServiceMockGetAll {
	if n == 0 {
		mmGetAll.mock.t.Fatalf("Times of SubscriptionServiceMock.GetAll mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetAll.expectedInvocations, n)
	mmGetAll.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetAll
}

func (mmGetAll *mSubscriptionServiceMockGetAll) invocationsDone() bool {
	if len(mmGetAll.expectations) == 0 && mmGetAll.defaultExpectation == nil && mmGetAll.mock.funcGetAll == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetAll.mock.afterGetAllCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetAll.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetAll implements mm_service.SubscriptionService
func (mmGetAll *SubscriptionServiceMock) GetAll(ctx context.Context) (spa1 []*domain.Subscription, err error) {
	mm_atomic.AddUint64(&mmGetAll.beforeGetAllCounter, 1)
	defer mm_atomic.AddUint64(&mmGetAll.afterGetAllCounter, 1)

	mmGetAll.t.Helper()

	if mmGetAll.inspectFuncGetAll != nil {
		mmGetAll.inspectFuncGetAll(ctx)
	}

	mm_params := SubscriptionServiceMockGetAllParams{ctx}

	// Record call args
	mmGetAll.GetAllMock.mutex.Lock()
	mmGetAll.GetAllMock.callArgs = append(mmGetAll.GetAllMock.callArgs, &mm_params)
	mmGetAll.GetAllMock.mutex.Unlock()

	for _, e := range mmGetAll.GetAllMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.spa1, e.results.err
		}
	}

	if mmGetAll.GetAllMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetAll.GetAllMock.defaultExpectation.Counter, 1)
		mm_want := mmGetAll.GetAllMock.defaultExpectation.params
		mm_want_ptrs := mmGetAll.GetAllMock.defaultExpectation.paramPtrs

		mm_got := SubscriptionServiceMockGetAllParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetAll.t.Errorf("SubscriptionServiceMock.GetAll got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetAll.GetAllMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetAll.t.Errorf("SubscriptionServiceMock.GetAll got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetAll.GetAllMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetAll.GetAllMock.defaultExpectation.results
		if mm_results == nil {
			mmGetAll.t.Fatal("No results are set for the SubscriptionServiceMock.GetAll")
		}
		return (*mm_results).spa1, (*mm_results).err
	}
	if mmGetAll.funcGetAll != nil {
		return mmGetAll.funcGetAll(ctx)
	}
	mmGetAll.t.Fatalf("Unexpected call to SubscriptionServiceMock.GetAll. %v", ctx)
	return
}

// GetAllAfterCounter returns a count of finished SubscriptionServiceMock.GetAll invocations
func (mmGetAll *SubscriptionServiceMock) GetAllAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAll.afterGetAllCounter)
}

// GetAllBeforeCounter returns a count of SubscriptionServiceMock.GetAll invocations
func (mmGetAll *SubscriptionServiceMock) GetAllBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAll.beforeGetAllCounter)
}

// Calls returns a list of arguments used in each call to SubscriptionServiceMock.GetAll.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetAll *mSubscriptionServiceMockGetAll) Calls() []*SubscriptionServiceMockGetAllParams {
	mmGetAll.mutex.RLock()

	argCopy := make([]*SubscriptionServiceMockGetAllParams, len(mmGetAll.callArgs))
	copy(argCopy, mmGetAll.callArgs)

	mmGetAll.mutex.RUnlock()

	return argCopy
}

// MinimockGetAllDone returns true if the count of the GetAll invocations corresponds
// the number of defined expectations
func (m *SubscriptionServiceMock) MinimockGetAllDone() bool {
	if m.GetAllMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetAllMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetAllMock.invocationsDone()
}

// MinimockGetAllInspect logs each unmet expectation
func (m *SubscriptionServiceMock) MinimockGetAllInspect() {
	for _, e := range m.GetAllMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SubscriptionServiceMock.GetAll at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetAllCounter := mm_atomic.LoadUint64(&m.afterGetAllCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetAllMock.defaultExpectation != nil && afterGetAllCounter < 1 {
		if m.GetAllMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SubscriptionServiceMock.GetAll at\n%s", m.GetAllMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SubscriptionServiceMock.GetAll at\n%s with params: %#v", m.GetAllMock.defaultExpectation.expectationOrigins.origin, *m.GetAllMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAll != nil && afterGetAllCounter < 1 {
		m.t.Errorf("Expected call to SubscriptionServiceMock.GetAll at\n%s", m.funcGetAllOrigin)
	}

	if !m.GetAllMock.invocationsDone() && afterGetAllCounter > 0 {
		m.t.Errorf("Expected %d calls to SubscriptionServiceMock.GetAll at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetAllMock.expectedInvocations), m.GetAllMock.expectedInvocationsOrigin, afterGetAllCounter)
	}
}

type mSubscriptionServiceMockGetByID struct {
	optional           bool
	mock               *SubscriptionServiceMock
	defaultExpectation *SubscriptionServiceMockGetByIDExpectation
	expectations       []*SubscriptionServiceMockGetByIDExpectation

	callArgs []*SubscriptionServiceMockGetByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SubscriptionServiceMockGetByIDExpectation specifies expectation struct of the SubscriptionService.GetByID
type SubscriptionServiceMockGetByIDExpectation struct {
	mock               *SubscriptionServiceMock
	params             *SubscriptionServiceMockGetByIDParams
	paramPtrs          *SubscriptionServiceMockGetByIDParamPtrs
	expectationOrigins SubscriptionServiceMockGetByIDExpectationOrigins
	results            *SubscriptionServiceMockGetByIDResults
	returnOrigin       string
	Counter            uint64
}

// SubscriptionServiceMockGetByIDParams contains parameters of the SubscriptionService.GetByID
type SubscriptionServiceMockGetByIDParams struct {
	ctx context.Context
	id  string
}

// SubscriptionServiceMockGetByIDParamPtrs contains pointers to parameters of the SubscriptionService.GetByID
type SubscriptionServiceMockGetByIDParamPtrs struct {
	ctx *context.Context
	id  *string
}

// SubscriptionServiceMockGetByIDResults contains results of the SubscriptionService.GetByID
type SubscriptionServiceMockGetByIDResults struct {
	sp1 *domain.Subscription
	err error
}

// SubscriptionServiceMockGetByIDOrigins contains origins of expectations of the SubscriptionService.GetByID
type SubscriptionServiceMockGetByIDExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByID *mSubscriptionServiceMockGetByID) Optional() *mSubscriptionServiceMockGetByID {
	mmGetByID.optional = true
	return mmGetByID
}

// Expect sets up expected params for SubscriptionService.GetByID
func (mmGetByID *mSubscriptionServiceMockGetByID) Expect(ctx context.Context, id string) *mSubscriptionServiceMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionServiceMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &SubscriptionServiceMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.paramPtrs != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionServiceMock.GetByID mock is already set by ExpectParams functions")
	}

	mmGetByID.defaultExpectation.params = &SubscriptionServiceMockGetByIDParams{ctx, id}
	mmGetByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByID.expectations {
		if minimock.Equal(e.params, mmGetByID.defaultExpectation.params) {
			mmGetByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByID.defaultExpectation.params)
		}
	}

	return mmGetByID
}

// ExpectCtxParam1 sets up expected param ctx for SubscriptionService.GetByID
func (mmGetByID *mSubscriptionServiceMockGetByID) ExpectCtxParam1(ctx context.Context) *mSubscriptionServiceMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionServiceMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &SubscriptionServiceMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionServiceMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &SubscriptionServiceMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByID
}

// ExpectIdParam2 sets up expected param id for SubscriptionService.GetByID
func (mmGetByID *mSubscriptionServiceMockGetByID) ExpectIdParam2(id string) *mSubscriptionServiceMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionServiceMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &SubscriptionServiceMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionServiceMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &SubscriptionServiceMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.id = &id
	mmGetByID.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetByID
}

// Inspect accepts an inspector function that has same arguments as the SubscriptionService.GetByID
func (mmGetByID *mSubscriptionServiceMockGetByID) Inspect(f func(ctx context.Context, id string)) *mSubscriptionServiceMockGetByID {
	if mmGetByID.mock.inspectFuncGetByID != nil {
		mmGetByID.mock.t.Fatalf("Inspect function is already set for SubscriptionServiceMock.GetByID")
	}

	mmGetByID.mock.inspectFuncGetByID = f

	return mmGetByID
}

// Return sets up results that will be returned by SubscriptionService.GetByID
func (mmGetByID *mSubscriptionServiceMockGetByID) Return(sp1 *domain.Subscription, err error) *SubscriptionServiceMock {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionServiceMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &SubscriptionServiceMockGetByIDExpectation{mock: mmGetByID.mock}
	}
	mmGetByID.defaultExpectation.results = &SubscriptionServiceMockGetByIDResults{sp1, err}
	mmGetByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// Set uses given function f to mock the SubscriptionService.GetByID method
func (mmGetByID *mSubscriptionServiceMockGetByID) Set(f func(ctx context.Context, id string) (sp1 *domain.Subscription, err error)) *SubscriptionServiceMock {
	if mmGetByID.defaultExpectation != nil {
		mmGetByID.mock.t.Fatalf("Default expectation is already set for the SubscriptionService.GetByID method")
	}

	if len(mmGetByID.expectations) > 0 {
		mmGetByID.mock.t.Fatalf("Some expectations are already set for the SubscriptionService.GetByID method")
	}

	mmGetByID.mock.funcGetByID = f
	mmGetByID.mock.funcGetByIDOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// When sets expectation for the SubscriptionService.GetByID which will trigger the result defined by the following
// Then helper
func (mmGetByID *mSubscriptionServiceMockGetByID) When(ctx context.Context, id string) *SubscriptionServiceMockGetByIDExpectation {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("SubscriptionServiceMock.GetByID mock is already set by Set")
	}

	expectation := &SubscriptionServiceMockGetByIDExpectation{
		mock:               mmGetByID.mock,
		params:             &SubscriptionServiceMockGetByIDParams{ctx, id},
		expectationOrigins: SubscriptionServiceMockGetByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByID.expectations = append(mmGetByID.expectations, expectation)
	return expectation
}

// Then sets up SubscriptionService.GetByID return parameters for the expectation previously defined by the When method
func (e *SubscriptionServiceMockGetByIDExpectation) Then(sp1 *domain.Subscription, err error) *SubscriptionServiceMock {
	e.results = &SubscriptionServiceMockGetByIDResults{sp1, err}
	return e.mock
}

// Times sets number of times SubscriptionService.GetByID should be invoked
func (mmGetByID *mSubscriptionServiceMockGetByID) Times(n uint64) *mSubscriptionServiceMockGetByID {
	if n == 0 {
		mmGetByID.mock.t.Fatalf("Times of SubscriptionServiceMock.GetByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByID.expectedInvocations, n)
	mmGetByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByID
}

func (mmGetByID *mSubscriptionServiceMockGetByID) invocationsDone() bool {
	if len(mmGetByID.expectations) == 0 && mmGetByID.defaultExpectation == nil && mmGetByID.mock.funcGetByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByID.mock.afterGetByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByID implements mm_service.SubscriptionService
func (mmGetByID *SubscriptionServiceMock) GetByID(ctx context.Context, id string) (sp1 *domain.Subscription, err error) {
	mm_atomic.AddUint64(&mmGetByID.beforeGetByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByID.afterGetByIDCounter, 1)

	mmGetByID.t.Helper()

	if mmGetByID.inspectFuncGetByID != nil {
		mmGetByID.inspectFuncGetByID(ctx, id)
	}

	mm_params := SubscriptionServiceMockGetByIDParams{ctx, id}

	// Record call args
	mmGetByID.GetByIDMock.mutex.Lock()
	mmGetByID.GetByIDMock.callArgs = append(mmGetByID.GetByIDMock.callArgs, &mm_params)
	mmGetByID.GetByIDMock.mutex.Unlock()

	for _, e := range mmGetByID.GetByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmGetByID.GetByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByID.GetByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByID.GetByIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByID.GetByIDMock.defaultExpectation.paramPtrs

		mm_got := SubscriptionServiceMockGetByIDParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByID.t.Errorf("SubscriptionServiceMock.GetByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetByID.t.Errorf("SubscriptionServiceMock.GetByID got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByID.t.Errorf("SubscriptionServiceMock.GetByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByID.GetByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByID.t.Fatal("No results are set for the SubscriptionServiceMock.GetByID")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmGetByID.funcGetByID != nil {
		return mmGetByID.funcGetByID(ctx, id)
	}
	mmGetByID.t.Fatalf("Unexpected call to SubscriptionServiceMock.GetByID. %v %v", ctx, id)
	return
}

// GetByIDAfterCounter returns a count of finished SubscriptionServiceMock.GetByID invocations
func (mmGetByID *SubscriptionServiceMock) GetByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.afterGetByIDCounter)
}

// GetByIDBeforeCounter returns a count of SubscriptionServiceMock.GetByID invocations
func (mmGetByID *SubscriptionServiceMock) GetByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.beforeGetByIDCounter)
}

// Calls returns a list of arguments used in each call to SubscriptionServiceMock.GetByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByID *mSubscriptionServiceMockGetByID) Calls() []*SubscriptionServiceMockGetByIDParams {
	mmGetByID.mutex.RLock()

	argCopy := make([]*SubscriptionServiceMockGetByIDParams, len(mmGetByID.callArgs))
	copy(argCopy, mmGetByID.callArgs)

	mmGetByID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByIDDone returns true if the count of the GetByID invocations corresponds
// the number of defined expectations
func (m *SubscriptionServiceMock) MinimockGetByIDDone() bool {
	if m.GetByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByIDMock.invocationsDone()
}

// MinimockGetByIDInspect logs each unmet expectation
func (m *SubscriptionServiceMock) MinimockGetByIDInspect() {
	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SubscriptionServiceMock.GetByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByIDCounter := mm_atomic.LoadUint64(&m.afterGetByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByIDMock.defaultExpectation != nil && afterGetByIDCounter < 1 {
		if m.GetByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SubscriptionServiceMock.GetByID at\n%s", m.GetByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SubscriptionServiceMock.GetByID at\n%s with params: %#v", m.GetByIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByID != nil && afterGetByIDCounter < 1 {
		m.t.Errorf("Expected call to SubscriptionServiceMock.GetByID at\n%s", m.funcGetByIDOrigin)
	}

	if !m.GetByIDMock.invocationsDone() && afterGetByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to SubscriptionServiceMock.GetByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByIDMock.expectedInvocations), m.GetByIDMock.expectedInvocationsOrigin, afterGetByIDCounter)
	}
}

type mSubscriptionServiceMockTotalCost struct {
	optional           bool
	mock               *SubscriptionServiceMock
	defaultExpectation *SubscriptionServiceMockTotalCostExpectation
	expectations       []*SubscriptionServiceMockTotalCostExpectation

	callArgs []*SubscriptionServiceMockTotalCostParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SubscriptionServiceMockTotalCostExpectation specifies expectation struct of the SubscriptionService.TotalCost
type SubscriptionServiceMockTotalCostExpectation struct {
	mock               *SubscriptionServiceMock
	params             *SubscriptionServiceMockTotalCostParams
	paramPtrs          *SubscriptionServiceMockTotalCostParamPtrs
	expectationOrigins SubscriptionServiceMockTotalCostExpectationOrigins
	results            *SubscriptionServiceMockTotalCostResults
	returnOrigin       string
	Counter            uint64
}

// SubscriptionServiceMockTotalCostParams contains parameters of the SubscriptionService.TotalCost
type SubscriptionServiceMockTotalCostParams struct {
	ctx         context.Context
	userID      *string
	serviceName *string
	from        *time.Time
	to          *time.Time
}

// SubscriptionServiceMockTotalCostParamPtrs contains pointers to parameters of the SubscriptionService.TotalCost
type SubscriptionServiceMockTotalCostParamPtrs struct {
	ctx         *context.Context
	userID      **string
	serviceName **string
	from        **time.Time
	to          **time.Time
}

// SubscriptionServiceMockTotalCostResults contains results of the SubscriptionService.TotalCost
type SubscriptionServiceMockTotalCostResults struct {
	i1  int
	err error
}

// SubscriptionServiceMockTotalCostOrigins contains origins of expectations of the SubscriptionService.TotalCost
type SubscriptionServiceMockTotalCostExpectationOrigins struct {
	origin            string
	originCtx         string
	originUserID      string
	originServiceName string
	originFrom        string
	originTo          string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmTotalCost *mSubscriptionServiceMockTotalCost) Optional() *mSubscriptionServiceMockTotalCost {
	mmTotalCost.optional = true
	return mmTotalCost
}

// Expect sets up expected params for SubscriptionService.TotalCost
func (mmTotalCost *mSubscriptionServiceMockTotalCost) Expect(ctx context.Context, userID *string, serviceName *string, from *time.Time, to *time.Time) *mSubscriptionServiceMockTotalCost {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionServiceMock.TotalCost mock is already set by Set")
	}

	if mmTotalCost.defaultExpectation == nil {
		mmTotalCost.defaultExpectation = &SubscriptionServiceMockTotalCostExpectation{}
	}

	if mmTotalCost.defaultExpectation.paramPtrs != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionServiceMock.TotalCost mock is already set by ExpectParams functions")
	}

	mmTotalCost.defaultExpectation.params = &SubscriptionServiceMockTotalCostParams{ctx, userID, serviceName, from, to}
	mmTotalCost.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmTotalCost.expectations {
		if minimock.Equal(e.params, mmTotalCost.defaultExpectation.params) {
			mmTotalCost.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmTotalCost.defaultExpectation.params)
		}
	}

	return mmTotalCost
}

// ExpectCtxParam1 sets up expected param ctx for SubscriptionService.TotalCost
func (mmTotalCost *mSubscriptionServiceMockTotalCost) ExpectCtxParam1(ctx context.Context) *mSubscriptionServiceMockTotalCost {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionServiceMock.TotalCost mock is already set by Set")
	}

	if mmTotalCost.defaultExpectation == nil {
		mmTotalCost.defaultExpectation = &SubscriptionServiceMockTotalCostExpectation{}
	}

	if mmTotalCost.defaultExpectation.params != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionServiceMock.TotalCost mock is already set by Expect")
	}

	if mmTotalCost.defaultExpectation.paramPtrs == nil {
		mmTotalCost.defaultExpectation.paramPtrs = &SubscriptionServiceMockTotalCostParamPtrs{}
	}
	mmTotalCost.defaultExpectation.paramPtrs.ctx = &ctx
	mmTotalCost.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmTotalCost
}

// ExpectUserIDParam2 sets up expected param userID for SubscriptionService.TotalCost
func (mmTotalCost *mSubscriptionServiceMockTotalCost) ExpectUserIDParam2(userID *string) *mSubscriptionServiceMockTotalCost {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionServiceMock.TotalCost mock is already set by Set")
	}

	if mmTotalCost.defaultExpectation == nil {
		mmTotalCost.defaultExpectation = &SubscriptionServiceMockTotalCostExpectation{}
	}

	if mmTotalCost.defaultExpectation.params != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionServiceMock.TotalCost mock is already set by Expect")
	}

	if mmTotalCost.defaultExpectation.paramPtrs == nil {
		mmTotalCost.defaultExpectation.paramPtrs = &SubscriptionServiceMockTotalCostParamPtrs{}
	}
	mmTotalCost.defaultExpectation.paramPtrs.userID = &userID
	mmTotalCost.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmTotalCost
}

// ExpectServiceNameParam3 sets up expected param serviceName for SubscriptionService.TotalCost
func (mmTotalCost *mSubscriptionServiceMockTotalCost) ExpectServiceNameParam3(serviceName *string) *mSubscriptionServiceMockTotalCost {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionServiceMock.TotalCost mock is already set by Set")
	}

	if mmTotalCost.defaultExpectation == nil {
		mmTotalCost.defaultExpectation = &SubscriptionServiceMockTotalCostExpectation{}
	}

	if mmTotalCost.defaultExpectation.params != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionServiceMock.TotalCost mock is already set by Expect")
	}

	if mmTotalCost.defaultExpectation.paramPtrs == nil {
		mmTotalCost.defaultExpectation.paramPtrs = &SubscriptionServiceMockTotalCostParamPtrs{}
	}
	mmTotalCost.defaultExpectation.paramPtrs.serviceName = &serviceName
	mmTotalCost.defaultExpectation.expectationOrigins.originServiceName = minimock.CallerInfo(1)

	return mmTotalCost
}

// ExpectFromParam4 sets up expected param from for SubscriptionService.TotalCost
func (mmTotalCost *mSubscriptionServiceMockTotalCost) ExpectFromParam4(from *time.Time) *mSubscriptionServiceMockTotalCost {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionServiceMock.TotalCost mock is already set by Set")
	}

	if mmTotalCost.defaultExpectation == nil {
		mmTotalCost.defaultExpectation = &SubscriptionServiceMockTotalCostExpectation{}
	}

	if mmTotalCost.defaultExpectation.params != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionServiceMock.TotalCost mock is already set by Expect")
	}

	if mmTotalCost.defaultExpectation.paramPtrs == nil {
		mmTotalCost.defaultExpectation.paramPtrs = &SubscriptionServiceMockTotalCostParamPtrs{}
	}
	mmTotalCost.defaultExpectation.paramPtrs.from = &from
	mmTotalCost.defaultExpectation.expectationOrigins.originFrom = minimock.CallerInfo(1)

	return mmTotalCost
}

// ExpectToParam5 sets up expected param to for SubscriptionService.TotalCost
func (mmTotalCost *mSubscriptionServiceMockTotalCost) ExpectToParam5(to *time.Time) *mSubscriptionServiceMockTotalCost {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionServiceMock.TotalCost mock is already set by Set")
	}

	if mmTotalCost.defaultExpectation == nil {
		mmTotalCost.defaultExpectation = &SubscriptionServiceMockTotalCostExpectation{}
	}

	if mmTotalCost.defaultExpectation.params != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionServiceMock.TotalCost mock is already set by Expect")
	}

	if mmTotalCost.defaultExpectation.paramPtrs == nil {
		mmTotalCost.defaultExpectation.paramPtrs = &SubscriptionServiceMockTotalCostParamPtrs{}
	}
	mmTotalCost.defaultExpectation.paramPtrs.to = &to
	mmTotalCost.defaultExpectation.expectationOrigins.originTo = minimock.CallerInfo(1)

	return mmTotalCost
}

// Inspect accepts an inspector function that has same arguments as the SubscriptionService.TotalCost
func (mmTotalCost *mSubscriptionServiceMockTotalCost) Inspect(f func(ctx context.Context, userID *string, serviceName *string, from *time.Time, to *time.Time)) *mSubscriptionServiceMockTotalCost {
	if mmTotalCost.mock.inspectFuncTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("Inspect function is already set for SubscriptionServiceMock.TotalCost")
	}

	mmTotalCost.mock.inspectFuncTotalCost = f

	return mmTotalCost
}

// Return sets up results that will be returned by SubscriptionService.TotalCost
func (mmTotalCost *mSubscriptionServiceMockTotalCost) Return(i1 int, err error) *SubscriptionServiceMock {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionServiceMock.TotalCost mock is already set by Set")
	}

	if mmTotalCost.defaultExpectation == nil {
		mmTotalCost.defaultExpectation = &SubscriptionServiceMockTotalCostExpectation{mock: mmTotalCost.mock}
	}
	mmTotalCost.defaultExpectation.results = &SubscriptionServiceMockTotalCostResults{i1, err}
	mmTotalCost.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmTotalCost.mock
}

// Set uses given function f to mock the SubscriptionService.TotalCost method
func (mmTotalCost *mSubscriptionServiceMockTotalCost) Set(f func(ctx context.Context, userID *string, serviceName *string, from *time.Time, to *time.Time) (i1 int, err error)) *SubscriptionServiceMock {
	if mmTotalCost.defaultExpectation != nil {
		mmTotalCost.mock.t.Fatalf("Default expectation is already set for the SubscriptionService.TotalCost method")
	}

	if len(mmTotalCost.expectations) > 0 {
		mmTotalCost.mock.t.Fatalf("Some expectations are already set for the SubscriptionService.TotalCost method")
	}

	mmTotalCost.mock.funcTotalCost = f
	mmTotalCost.mock.funcTotalCostOrigin = minimock.CallerInfo(1)
	return mmTotalCost.mock
}

// When sets expectation for the SubscriptionService.TotalCost which will trigger the result defined by the following
// Then helper
func (mmTotalCost *mSubscriptionServiceMockTotalCost) When(ctx context.Context, userID *string, serviceName *string, from *time.Time, to *time.Time) *SubscriptionServiceMockTotalCostExpectation {
	if mmTotalCost.mock.funcTotalCost != nil {
		mmTotalCost.mock.t.Fatalf("SubscriptionServiceMock.TotalCost mock is already set by Set")
	}

	expectation := &SubscriptionServiceMockTotalCostExpectation{
		mock:               mmTotalCost.mock,
		params:             &SubscriptionServiceMockTotalCostParams{ctx, userID, serviceName, from, to},
		expectationOrigins: SubscriptionServiceMockTotalCostExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmTotalCost.expectations = append(mmTotalCost.expectations, expectation)
	return expectation
}

// Then sets up SubscriptionService.TotalCost return parameters for the expectation previously defined by the When method
func (e *SubscriptionServiceMockTotalCostExpectation) Then(i1 int, err error) *SubscriptionServiceMock {
	e.results = &SubscriptionServiceMockTotalCostResults{i1, err}
	return e.mock
}

// Times sets number of times SubscriptionService.TotalCost should be invoked
func (mmTotalCost *mSubscriptionServiceMockTotalCost) Times(n uint64) *mSubscriptionServiceMockTotalCost {
	if n == 0 {
		mmTotalCost.mock.t.Fatalf("Times of SubscriptionServiceMock.TotalCost mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmTotalCost.expectedInvocations, n)
	mmTotalCost.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmTotalCost
}

func (mmTotalCost *mSubscriptionServiceMockTotalCost) invocationsDone() bool {
	if len(mmTotalCost.expectations) == 0 && mmTotalCost.defaultExpectation == nil && mmTotalCost.mock.funcTotalCost == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmTotalCost.mock.afterTotalCostCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmTotalCost.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// TotalCost implements mm_service.SubscriptionService
func (mmTotalCost *SubscriptionServiceMock) TotalCost(ctx context.Context, userID *string, serviceName *string, from *time.Time, to *time.Time) (i1 int, err error) {
	mm_atomic.AddUint64(&mmTotalCost.beforeTotalCostCounter, 1)
	defer mm_atomic.AddUint64(&mmTotalCost.afterTotalCostCounter, 1)

	mmTotalCost.t.Helper()

	if mmTotalCost.inspectFuncTotalCost != nil {
		mmTotalCost.inspectFuncTotalCost(ctx, userID, serviceName, from, to)
	}

	mm_params := SubscriptionServiceMockTotalCostParams{ctx, userID, serviceName, from, to}

	// Record call args
	mmTotalCost.TotalCostMock.mutex.Lock()
	mmTotalCost.TotalCostMock.callArgs = append(mmTotalCost.TotalCostMock.callArgs, &mm_params)
	mmTotalCost.TotalCostMock.mutex.Unlock()

	for _, e := range mmTotalCost.TotalCostMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmTotalCost.TotalCostMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmTotalCost.TotalCostMock.defaultExpectation.Counter, 1)
		mm_want := mmTotalCost.TotalCostMock.defaultExpectation.params
		mm_want_ptrs := mmTotalCost.TotalCostMock.defaultExpectation.paramPtrs

		mm_got := SubscriptionServiceMockTotalCostParams{ctx, userID, serviceName, from, to}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmTotalCost.t.Errorf("SubscriptionServiceMock.TotalCost got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmTotalCost.TotalCostMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmTotalCost.t.Errorf("SubscriptionServiceMock.TotalCost got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmTotalCost.TotalCostMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.serviceName != nil && !minimock.Equal(*mm_want_ptrs.serviceName, mm_got.serviceName) {
				mmTotalCost.t.Errorf("SubscriptionServiceMock.TotalCost got unexpected parameter serviceName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmTotalCost.TotalCostMock.defaultExpectation.expectationOrigins.originServiceName, *mm_want_ptrs.serviceName, mm_got.serviceName, minimock.Diff(*mm_want_ptrs.serviceName, mm_got.serviceName))
			}

			if mm_want_ptrs.from != nil && !minimock.Equal(*mm_want_ptrs.from, mm_got.from) {
				mmTotalCost.t.Errorf("SubscriptionServiceMock.TotalCost got unexpected parameter from, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmTotalCost.TotalCostMock.defaultExpectation.expectationOrigins.originFrom, *mm_want_ptrs.from, mm_got.from, minimock.Diff(*mm_want_ptrs.from, mm_got.from))
			}

			if mm_want_ptrs.to != nil && !minimock.Equal(*mm_want_ptrs.to, mm_got.to) {
				mmTotalCost.t.Errorf("SubscriptionServiceMock.TotalCost got unexpected parameter to, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmTotalCost.TotalCostMock.defaultExpectation.expectationOrigins.originTo, *mm_want_ptrs.to, mm_got.to, minimock.Diff(*mm_want_ptrs.to, mm_got.to))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmTotalCost.t.Errorf("SubscriptionServiceMock.TotalCost got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmTotalCost.TotalCostMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmTotalCost.TotalCostMock.defaultExpectation.results
		if mm_results == nil {
			mmTotalCost.t.Fatal("No results are set for the SubscriptionServiceMock.TotalCost")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmTotalCost.funcTotalCost != nil {
		return mmTotalCost.funcTotalCost(ctx, userID, serviceName, from, to)
	}
	mmTotalCost.t.Fatalf("Unexpected call to SubscriptionServiceMock.TotalCost. %v %v %v %v %v", ctx, userID, serviceName, from, to)
	return
}

// TotalCostAfterCounter returns a count of finished SubscriptionServiceMock.TotalCost invocations
func (mmTotalCost *SubscriptionServiceMock) TotalCostAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTotalCost.afterTotalCostCounter)
}

// TotalCostBeforeCounter returns a count of SubscriptionServiceMock.TotalCost invocations
func (mmTotalCost *SubscriptionServiceMock) TotalCostBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTotalCost.beforeTotalCostCounter)
}

// Calls returns a list of arguments used in each call to SubscriptionServiceMock.TotalCost.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmTotalCost *mSubscriptionServiceMockTotalCost) Calls() []*SubscriptionServiceMockTotalCostParams {
	mmTotalCost.mutex.RLock()

	argCopy := make([]*SubscriptionServiceMockTotalCostParams, len(mmTotalCost.callArgs))
	copy(argCopy, mmTotalCost.callArgs)

	mmTotalCost.mutex.RUnlock()

	return argCopy
}

// MinimockTotalCostDone returns true if the count of the TotalCost invocations corresponds
// the number of defined expectations
func (m *SubscriptionServiceMock) MinimockTotalCostDone() bool {
	if m.TotalCostMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.TotalCostMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.TotalCostMock.invocationsDone()
}

// MinimockTotalCostInspect logs each unmet expectation
func (m *SubscriptionServiceMock) MinimockTotalCostInspect() {
	for _, e := range m.TotalCostMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SubscriptionServiceMock.TotalCost at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterTotalCostCounter := mm_atomic.LoadUint64(&m.afterTotalCostCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.TotalCostMock.defaultExpectation != nil && afterTotalCostCounter < 1 {
		if m.TotalCostMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SubscriptionServiceMock.TotalCost at\n%s", m.TotalCostMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SubscriptionServiceMock.TotalCost at\n%s with params: %#v", m.TotalCostMock.defaultExpectation.expectationOrigins.origin, *m.TotalCostMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcTotalCost != nil && afterTotalCostCounter < 1 {
		m.t.Errorf("Expected call to SubscriptionServiceMock.TotalCost at\n%s", m.funcTotalCostOrigin)
	}

	if !m.TotalCostMock.invocationsDone() && afterTotalCostCounter > 0 {
		m.t.Errorf("Expected %d calls to SubscriptionServiceMock.TotalCost at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.TotalCostMock.expectedInvocations), m.TotalCostMock.expectedInvocationsOrigin, afterTotalCostCounter)
	}
}

type mSubscriptionServiceMockUpdate struct {
	optional           bool
	mock               *SubscriptionServiceMock
	defaultExpectation *SubscriptionServiceMockUpdateExpectation
	expectations       []*SubscriptionServiceMockUpdateExpectation

	callArgs []*SubscriptionServiceMockUpdateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SubscriptionServiceMockUpdateExpectation specifies expectation struct of the SubscriptionService.Update
type SubscriptionServiceMockUpdateExpectation struct {
	mock               *SubscriptionServiceMock
	params             *SubscriptionServiceMockUpdateParams
	paramPtrs          *SubscriptionServiceMockUpdateParamPtrs
	expectationOrigins SubscriptionServiceMockUpdateExpectationOrigins
	results            *SubscriptionServiceMockUpdateResults
	returnOrigin       string
	Counter            uint64
}

// SubscriptionServiceMockUpdateParams contains parameters of the SubscriptionService.Update
type SubscriptionServiceMockUpdateParams struct {
	ctx context.Context
	sub *domain.Subscription
}

// SubscriptionServiceMockUpdateParamPtrs contains pointers to parameters of the SubscriptionService.Update
type SubscriptionServiceMockUpdateParamPtrs struct {
	ctx *context.Context
	sub **domain.Subscription
}

// SubscriptionServiceMockUpdateResults contains results of the SubscriptionService.Update
type SubscriptionServiceMockUpdateResults struct {
	sp1 *domain.Subscription
	err error
}

// SubscriptionServiceMockUpdateOrigins contains origins of expectations of the SubscriptionService.Update
type SubscriptionServiceMockUpdateExpectationOrigins struct {
	origin    string
	originCtx string
	originSub string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdate *mSubscriptionServiceMockUpdate) Optional() *mSubscriptionServiceMockUpdate {
	mmUpdate.optional = true
	return mmUpdate
}

// Expect sets up expected params for SubscriptionService.Update
func (mmUpdate *mSubscriptionServiceMockUpdate) Expect(ctx context.Context, sub *domain.Subscription) *mSubscriptionServiceMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionServiceMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &SubscriptionServiceMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.paramPtrs != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionServiceMock.Update mock is already set by ExpectParams functions")
	}

	mmUpdate.defaultExpectation.params = &SubscriptionServiceMockUpdateParams{ctx, sub}
	mmUpdate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdate.expectations {
		if minimock.Equal(e.params, mmUpdate.defaultExpectation.params) {
			mmUpdate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdate.defaultExpectation.params)
		}
	}

	return mmUpdate
}

// ExpectCtxParam1 sets up expected param ctx for SubscriptionService.Update
func (mmUpdate *mSubscriptionServiceMockUpdate) ExpectCtxParam1(ctx context.Context) *mSubscriptionServiceMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionServiceMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &SubscriptionServiceMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.params != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionServiceMock.Update mock is already set by Expect")
	}

	if mmUpdate.defaultExpectation.paramPtrs == nil {
		mmUpdate.defaultExpectation.paramPtrs = &SubscriptionServiceMockUpdateParamPtrs{}
	}
	mmUpdate.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdate
}

// ExpectSubParam2 sets up expected param sub for SubscriptionService.Update
func (mmUpdate *mSubscriptionServiceMockUpdate) ExpectSubParam2(sub *domain.Subscription) *mSubscriptionServiceMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionServiceMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &SubscriptionServiceMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.params != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionServiceMock.Update mock is already set by Expect")
	}

	if mmUpdate.defaultExpectation.paramPtrs == nil {
		mmUpdate.defaultExpectation.paramPtrs = &SubscriptionServiceMockUpdateParamPtrs{}
	}
	mmUpdate.defaultExpectation.paramPtrs.sub = &sub
	mmUpdate.defaultExpectation.expectationOrigins.originSub = minimock.CallerInfo(1)

	return mmUpdate
}

// Inspect accepts an inspector function that has same arguments as the SubscriptionService.Update
func (mmUpdate *mSubscriptionServiceMockUpdate) Inspect(f func(ctx context.Context, sub *domain.Subscription)) *mSubscriptionServiceMockUpdate {
	if mmUpdate.mock.inspectFuncUpdate != nil {
		mmUpdate.mock.t.Fatalf("Inspect function is already set for SubscriptionServiceMock.Update")
	}

	mmUpdate.mock.inspectFuncUpdate = f

	return mmUpdate
}

// Return sets up results that will be returned by SubscriptionService.Update
func (mmUpdate *mSubscriptionServiceMockUpdate) Return(sp1 *domain.Subscription, err error) *SubscriptionServiceMock {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionServiceMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &SubscriptionServiceMockUpdateExpectation{mock: mmUpdate.mock}
	}
	mmUpdate.defaultExpectation.results = &SubscriptionServiceMockUpdateResults{sp1, err}
	mmUpdate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdate.mock
}

// Set uses given function f to mock the SubscriptionService.Update method
func (mmUpdate *mSubscriptionServiceMockUpdate) Set(f func(ctx context.Context, sub *domain.Subscription) (sp1 *domain.Subscription, err error)) *SubscriptionServiceMock {
	if mmUpdate.defaultExpectation != nil {
		mmUpdate.mock.t.Fatalf("Default expectation is already set for the SubscriptionService.Update method")
	}

	if len(mmUpdate.expectations) > 0 {
		mmUpdate.mock.t.Fatalf("Some expectations are already set for the SubscriptionService.Update method")
	}

	mmUpdate.mock.funcUpdate = f
	mmUpdate.mock.funcUpdateOrigin = minimock.CallerInfo(1)
	return mmUpdate.mock
}

// When sets expectation for the SubscriptionService.Update which will trigger the result defined by the following
// Then helper
func (mmUpdate *mSubscriptionServiceMockUpdate) When(ctx context.Context, sub *domain.Subscription) *SubscriptionServiceMockUpdateExpectation {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("SubscriptionServiceMock.Update mock is already set by Set")
	}

	expectation := &SubscriptionServiceMockUpdateExpectation{
		mock:               mmUpdate.mock,
		params:             &SubscriptionServiceMockUpdateParams{ctx, sub},
		expectationOrigins: SubscriptionServiceMockUpdateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdate.expectations = append(mmUpdate.expectations, expectation)
	return expectation
}

// Then sets up SubscriptionService.Update return parameters for the expectation previously defined by the When method
func (e *SubscriptionServiceMockUpdateExpectation) Then(sp1 *domain.Subscription, err error) *SubscriptionServiceMock {
	e.results = &SubscriptionServiceMockUpdateResults{sp1, err}
	return e.mock
}

// Times sets number of times SubscriptionService.Update should be invoked
func (mmUpdate *mSubscriptionServiceMockUpdate) Times(n uint64) *mSubscriptionServiceMockUpdate {
	if n == 0 {
		mmUpdate.mock.t.Fatalf("Times of SubscriptionServiceMock.Update mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdate.expectedInvocations, n)
	mmUpdate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdate
}

func (mmUpdate *mSubscriptionServiceMockUpdate) invocationsDone() bool {
	if len(mmUpdate.expectations) == 0 && mmUpdate.defaultExpectation == nil && mmUpdate.mock.funcUpdate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdate.mock.afterUpdateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Update implements mm_service.SubscriptionService
func (mmUpdate *SubscriptionServiceMock) Update(ctx context.Context, sub *domain.Subscription) (sp1 *domain.Subscription, err error) {
	mm_atomic.AddUint64(&mmUpdate.beforeUpdateCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdate.afterUpdateCounter, 1)

	mmUpdate.t.Helper()

	if mmUpdate.inspectFuncUpdate != nil {
		mmUpdate.inspectFuncUpdate(ctx, sub)
	}

	mm_params := SubscriptionServiceMockUpdateParams{ctx, sub}

	// Record call args
	mmUpdate.UpdateMock.mutex.Lock()
	mmUpdate.UpdateMock.callArgs = append(mmUpdate.UpdateMock.callArgs, &mm_params)
	mmUpdate.UpdateMock.mutex.Unlock()

	for _, e := range mmUpdate.UpdateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmUpdate.UpdateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdate.UpdateMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdate.UpdateMock.defaultExpectation.params
		mm_want_ptrs := mmUpdate.UpdateMock.defaultExpectation.paramPtrs

		mm_got := SubscriptionServiceMockUpdateParams{ctx, sub}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdate.t.Errorf("SubscriptionServiceMock.Update got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sub != nil && !minimock.Equal(*mm_want_ptrs.sub, mm_got.sub) {
				mmUpdate.t.Errorf("SubscriptionServiceMock.Update got unexpected parameter sub, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.originSub, *mm_want_ptrs.sub, mm_got.sub, minimock.Diff(*mm_want_ptrs.sub, mm_got.sub))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdate.t.Errorf("SubscriptionServiceMock.Update got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdate.UpdateMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdate.t.Fatal("No results are set for the SubscriptionServiceMock.Update")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmUpdate.funcUpdate != nil {
		return mmUpdate.funcUpdate(ctx, sub)
	}
	mmUpdate.t.Fatalf("Unexpected call to SubscriptionServiceMock.Update. %v %v", ctx, sub)
	return
}

// UpdateAfterCounter returns a count of finished SubscriptionServiceMock.Update invocations
func (mmUpdate *SubscriptionServiceMock) UpdateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdate.afterUpdateCounter)
}

// UpdateBeforeCounter returns a count of SubscriptionServiceMock.Update invocations
func (mmUpdate *SubscriptionServiceMock) UpdateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdate.beforeUpdateCounter)
}

// Calls returns a list of arguments used in each call to SubscriptionServiceMock.Update.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdate *mSubscriptionServiceMockUpdate) Calls() []*SubscriptionServiceMockUpdateParams {
	mmUpdate.mutex.RLock()

	argCopy := make([]*SubscriptionServiceMockUpdateParams, len(mmUpdate.callArgs))
	copy(argCopy, mmUpdate.callArgs)

	mmUpdate.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateDone returns true if the count of the Update invocations corresponds
// the number of defined expectations
func (m *SubscriptionServiceMock) MinimockUpdateDone() bool {
	if m.UpdateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateMock.invocationsDone()
}

// MinimockUpdateInspect logs each unmet expectation
func (m *SubscriptionServiceMock) MinimockUpdateInspect() {
	for _, e := range m.UpdateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SubscriptionServiceMock.Update at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateCounter := mm_atomic.LoadUint64(&m.afterUpdateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateMock.defaultExpectation != nil && afterUpdateCounter < 1 {
		if m.UpdateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SubscriptionServiceMock.Update at\n%s", m.UpdateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SubscriptionServiceMock.Update at\n%s with params: %#v", m.UpdateMock.defaultExpectation.expectationOrigins.origin, *m.UpdateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdate != nil && afterUpdateCounter < 1 {
		m.t.Errorf("Expected call to SubscriptionServiceMock.Update at\n%s", m.funcUpdateOrigin)
	}

	if !m.UpdateMock.invocationsDone() && afterUpdateCounter > 0 {
		m.t.Errorf("Expected %d calls to SubscriptionServiceMock.Update at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateMock.expectedInvocations), m.UpdateMock.expectedInvocationsOrigin, afterUpdateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *SubscriptionServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockDeleteInspect()

			m.MinimockGetAllInspect()

			m.MinimockGetByIDInspect()

			m.MinimockTotalCostInspect()

			m.MinimockUpdateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *SubscriptionServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *SubscriptionServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockDeleteDone() &&
		m.MinimockGetAllDone() &&
		m.MinimockGetByIDDone() &&
		m.MinimockTotalCostDone() &&
		m.MinimockUpdateDone()
}
